### ISSUE TITLE
Better advice for referencing

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#1064]
In section 1.1, do a better job at recommending how to reference ASPECT.

**Comment by bangerth** [comment]
Also update the reference to the manual with the *version* of ASPECT. (Needs to go into the release task list as well.)

**Comment by bangerth** [comment]
Same text exists on the website.

**Comment by jaustermann** [comment]
The text on the website does not include the Acknowledgement section ... but it probably should?

**Comment by bangerth** [comment]
Yes, it should.

**Comment by ljhwang** [comment]
Since you version the manual, I would suggest that you put the version number in the bibtek.  Hence, I would also make this a required reference for now in lieu of properly mentioning version in the text.  

Mentioning the website is perhaps redundant as if they have the manual, should the website not already be in the manual?  What is the goal in mentioning the website?

**Comment by bangerth** [comment]
Yes, I think we ought to get rid of the reference to the website.

**Comment by lkellogg** [comment]
The library types would also recommend not referencing both the website AND the manual.

**Comment by ljhwang** [comment]
CLAIM: I will work on this ....

**Comment by jaustermann** [comment]
Regarding @lkellogg's comment: I would not put the version number in the bibtex because the version that might be used in the paper might not be the same version number in the manual. For example if someone doesn't update his/her code for a while but then checks the online manual on how to cite it. I would simply say that if Aspect is used the version number should be stated. 
I agree that citing the website is redundant and I think some journals don't even allow citing websites anymore so I would just stick with recommending citing Kronbichler and the manual.

**Comment by bangerth** [comment]
See #1087 and #1092. The same changes now also have to be done on the website.

**Comment by ljhwang** [comment]
Version number is now in the manual bibtek but @bangerth is there a way to automatically import from VERSION into the string? This will ensure that the bibtek stays in sync. 
@jaustermann A user should download the manual with the package. I would hope most users would know to use the version of the manual they downloaded.  This does happen and vice versa. Always best to check VERSION.

**Comment by tjhei** [comment]
> A user should download the manual with the package

We don't include the pdf inside the repository because it is a) big and b) changes too often.

**Comment by tjhei** [comment]
> Version number is now in the manual bibtek but @bangerth is there a way to automatically import from VERSION into the string?

I don't think this will work. We can not put the current RC (currently 1.5.0) into the manual, because that is not released yet. Version 1.5.0 might never exist if we go to 2.0 directly. That means importing it automatically won't work anyways.

**Comment by tjhei** [comment]
Note: any change to the manual also needs to be done at http://aspect.dealii.org/publications.html

**Comment by tjhei** [comment]
Finally, didn't we want to use cite.html exclusively? (see #1014)

**Comment by gassmoeller** [comment]
We updated the manual with the canonical reference, so this is partially resolved. Lets discuss #1014 separately in that PR.
