### ISSUE TITLE
ASPECT 2.0

### ISSUE THREAD

**Issue by gassmoeller** [geodynamics/aspect#1090]
List of Todos that should be included in 2.0:
- [x] Rename initial conditions and boundary conditions directories to identical structure:
  initial/boundary_property
- ~~[ ]~~ Rename parameter file subsection to consistently reflect the plugin name (automatically)
- [x] List of initial conditions (+ comp initial conditions)
- ~~[ ]~~ Pull apart compound initial conditions and boundary conditions
- [x] Remove reference_... functions from material model
- [x] Rename tracers to particles everywhere (cookbooks, parameter files, code, manual)
- ~~[ ]~~ Move as much particle property functionality into comp. Initial conditions as possible
- ~~[ ]~~ Officially support to have one plugin for different purposes (e.g. initial temperature + initial composition)

**Comment by jdannberg** [comment]
Regarding point 3: List of initial conditions (+ comp initial conditions)
One point that doesn't necessarily require more than 1 or 2 lines of changes in the input files could be the feature to allow using several initial conditions, and to be able to add them/take the maximum etc. This could be done similarly to the heating models, where we specify a list of models that should be used instead of the parameter `set Model name`.

**Comment by gassmoeller** [comment]
Lets move the still open points to the next major release (sometimes in the far future). They did not seem important enough for anyone to implement them during the more than one year before 2.0, and they are not easy or quick to implement.

**Comment by gassmoeller** [comment]
Everything in this issue has been addressed or postponed into other points, and we track the progress of 2.0 in the milestone, so I will close this meta issue.
