### ISSUE TITLE
Investigate why output changes after sparsity pattern optimization

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#1113]
#1100 modifies how the sparsity pattern is created for the DG case. In principle, this should only reduce the number of extra zeros in the sparse matrix (we unnecessarily allocate nonzero entries for a great number of entries that will ultimately never be set to anything). That pull request was merged, but I realize that it actually changes the number of iterations as well as the output for a number of tests, and I don't understand that.

@yinghe616 -- do you happen to know why this is happening?

**Comment by yinghe616** [comment]
@bangerth, Yes, I asked the same question to @tjhei before, and he gave me a reasonable explanation. If you looked at the output, it increased the iterations of advection fields which use continuous FEM but not the one using DG. Before applying the new DG sparse pattern, we assigned  the face couplings to every fields, so there are much larger nonzero numbers (therefore, more memory allocation). The preconditioner for the advection fields is ILU, so the number iterations can be increased due to the less memory? Does it make sense to you?

**Comment by bangerth** [comment]
Hm. So are you saying that because we now create smaller matrices, that the ILU preconditioner is worse and consequently we need more iterations?

**Comment by yinghe616** [comment]
Yes, that's the only good explanation so far... but the matrix size also changes,  so I think the more iterations doesn't mean more time cost.

**Comment by bangerth** [comment]
Yes, the smaller matrix may still make it faster or at least not much slower.

@tjhei -- this allays my concerns. If you are also unconcerned, please close this issue.

**Comment by bangerth** [comment]
For the record, the other changes in #1100 update the `statistics` file and print the time and time step size with more precision. This is unrelated to the patch -- the high precision is due to #830 but the statistics file affected by #1100 weren't updated by #830. In other words, these changes are ok as well.

**Comment by tjhei** [comment]
> @tjhei -- this allays my concerns. If you are also unconcerned, please close this issue.

Yes, I think the better ILU explains the changes.
