### ISSUE TITLE
The Raleigh number for the  cookbook of a 2d-convection box

### ISSUE THREAD

**Issue by yinghe616** [geodynamics/aspect#1128]
In the cookbook of a 2d-convection box in the manual, it mentions that the  Raleigh number is calculated by setting several parameters to be one including the heat capacity C_p= 1. However, in the prm file 
aspect/cookbooks/convection-box.prm
it doesn't reset the value of C_p, which means this example uses a default value C_p=1250. So which one should be right when calculating the Raleigh number using the formula mentioned there Ra=(g\alpha)/(\eta \kappa)? C_p=1 or C_p=1250
Is there a formula including variation of all the parameters, so it can be calculated automatically?

@egpuckett , you may be also interested to know this.

![2d_convection](https://cloud.githubusercontent.com/assets/12536604/16864476/cee5cf10-4a11-11e6-902c-88bf830c081b.png)

**Comment by jdannberg** [comment]
But in aspect/cookbooks/convection-box.prm (line 125) there is a section

> subsection Material model
>  set Model name = simple # default:
>
>  subsection Simple model
>    set Reference density             = 1
>    set Reference specific heat       = 1
>    set Reference temperature         = 0
>    set Thermal conductivity          = 1
>    set Thermal expansion coefficient = 1e-10
>    set Viscosity                     = 1
>  end
>end

This sets the parameters exactly as they are described in the text (in particular, Reference specific heat = 1). Or is this not the input file you mean?

**Comment by yinghe616** [comment]
@jdannberg , thanks. So I think I misunderstood by those names... heat capacity C_p which is first introduced at the page 11 of the manual and used almost everywhere in those equations... However, in the prm, it is replaced by the name Reference specific heat, where the notation is NON-capitalized cp. I think most first timer user naturally search heat capacity C_p, and there does has such parameters in the parameter section....  so should they be combined? or at least mentioned somewhere in page 11 they are equivalent?

**Comment by jdannberg** [comment]
Yes, this is a good point, the notation in the description of the material models and in the general section of the manual should be consistent, so we should probably change it to C_p everywhere.

**Comment by egpuckett** [comment]
@ yinghe616:  Some of what is written in this Cookbook 5.2.1 is simply incorrect. In particular, note that the Rayleigh number is incorrectly defined. One can see this by noting that it's not a nondimensional number; i.e., it is a dimensional quantity.  In addition, the name Rayleigh is not spelled correctly :-)

Furthermore, @jdannberg  and @tjhei have a different method for running 'nondimensional' problems in ASPECT, but their branch has not been pulled into the master branch yet.

BTW I believe this cookbook is based on the first problem in the Blankenbach benchmark paper. 

I have a simple problem that is a computation of Turcotte's linearized stability analysis in his book "Geodynamics" that I plan to replace with this problem with, since it is an example most first year graduate students in Geophysics / Mantle Convection will be familiar with , I would like to move the Blankenbach cookbook (5.2.1. "Convection in a 2D box") further down in the cookbook section, say to 5.2.2 or beyond soits not the first problem in the cookbook chapter of the manual.This is  assuming @bangerth, @tjhei, @jdannberg , and @gassmoeller are amenable to moving the current section 5.2.1 "Convection in a 2D box" from it's place as the first cookbook in the Cookbook Chapter. 

This was a starter project Issue at the Hackathon, but it appears to have disappeared.  @bangerth did you remove this issue?

**Comment by jdannberg** [comment]
Okay, for the C_p notation I've opened a pull request here: #1129.

**Comment by egpuckett** [comment]
I agree with @jdannberg about standardizing the notation for the 'specific heat _at constant pressure_' to C_p everywhere in the manual.  However, note that 

>  The heat capacity C of a material (or gas or fluid) is not the same as the specific heat S of the same material. The relation between S and C is C = (mass of material) x (specific heat of material). 

This quote is from  

> [http://www.iun.edu/~cpanhd/C101webnotes/matter-and-energy/specificheat.html](url)

which seems to be a reasonable introduction to specific heat and heat capacity, except that it doesn't distinguish between specific heat _at constant pressure_', C_p, and specific heat _at constant volume_', C_v. 

Wikipedia's article on 'Heat Capacity' 

> [https://en.wikipedia.org/wiki/Heat_capacity](url)

appears to use capital C to denote _Heat Capacity_ and lower case c to denote _specific heat capacity_ , which is what we're refering to when we write `_specific heat_'.

The distinction is important in thermodynamics in general since in that case all thermodynamic quantities can be expressed as a function of any two thermodynamic quantities. However, in the Mantle Convection equations we're approximating, at least in the standard Boussinesq form, we remove one of those independent quantities by assuming that the material (fluid) is incompressible. This may or may not have any relation to the reason we see the specific heat at constant pressure', C_p in the standard Boussinesq form of the Mantle Convection equations we're approximating.  that requires some thought.

**Comment by jdannberg** [comment]
I also opened another pull request for that fixes some things in the convection box cookbook: #1130.
@egpuckett, did you notice anything else that was incorrect?
And yes, this cookbook is based on the Blankenbach benchmark, we even compare our results to the ones from Blankenbach. 

And of course it would be great if you could add the convection box example from Turcotte and Schubert! We can still discuss which of those should be the first cookbook; right now the first cookbook explains in quite some detail how the input file looks like, how to visualize the results, debug/optimized mode, and some other things. It would be quite some effort to write another cookbook that explains everything in so much detail, so maybe we could also just rename this cookbook to something like "Convection in a 2d box based on the Blankenbach benchmark", and add your cookbook as the second one?

**Comment by egpuckett** [comment]
> We can still discuss which of those should be the first cookbook; right now the first cookbook explains in quite some detail how the input file looks like, how to visualize the results, debug/optimized mode, and some other things. It would be quite some effort to write another cookbook that explains everything in so much detail, so maybe we could also just rename this cookbook to something like "Convection in a 2d box based on the Blankenbach benchmark", and add your cookbook as the second one?

Sure!  My thinking was to have first year students who have seen the material on linearized stability analysis in 'Geodynamics' compute the same solution as the first thing they do in ASPECT. What would you think of cutting and pasting or just plain copying the material on 

>  ... how the input file looks like, how to visualize the results, debug/optimized mode, and some other things. 

into this example?

**Comment by jdannberg** [comment]
> Sure! My thinking was to have first year students who have seen the material on linearized stability analysis in 'Geodynamics' compute the same solution as the first thing they do in ASPECT. 

Yes, that sounds like a great idea!

>What would you think of cutting and pasting or just plain copying the material on
>
> >   ... how the input file looks like, how to visualize the results, debug/optimized mode, and some other things.
> 
> into this example?

In principle, yes, but it is not as easy as that. All the explanations contain the input/output/visualization of that specific case, so you would have to make new files for all of these things. 

@bangerth, what do you think?

**Comment by bangerth** [comment]
I'm all for more cookbooks, and I don't particularly care about the order though thought has to be given to the issue of how to best present material in order. When writing new sections, I often try to structure the text in ways that allow me to not only talk about the particular problem at hand, but also look at other parts of ASPECT readers may not have seen yet. This makes it a bit awkward to just bump a section down because it would now introduce material readers should already have encountered in previous sections.

If we can find a way to just replace the specific model used in that section but keep the surrounding text in place, then I'm all fine with this.

**Comment by bangerth** [comment]
I think we have addressed the specific points raised here. The general issue of more cookbooks of course remains.
