### ISSUE TITLE
Use VectorTools::interpolate() with a mask

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#1141]
With the merge of https://github.com/dealii/dealii/pull/2838, we can now select individual components of the solution to be interpolated in VectorTools::interpolate(). This may simplifiy some code introduced in #1007, as well as the place where we interpolate initial conditions.

**Comment by bangerth** [comment]
@class4kayaker -- since you wrote the code in https://github.com/dealii/dealii/pull/2838, are you interested in tackling this? It would have to be guarded by `#if DEAL_II_VERSION_GTE(...)` but would allow us to remove the old code at one point in the future.

**Comment by bangerth** [comment]
Also requires https://github.com/dealii/dealii/pull/2858

**Comment by class4kayaker** [comment]
I can get to work on this. I will need to look into how to shift the current interfaces to Deal.II functions in a reasonable manner though.

**Comment by bangerth** [comment]
You can take #1133 as an example of how to switch an existing implementation to a new interface based on `#ifdef`s.

**Comment by ian-r-rose** [comment]
This should also make it possible to remove the `interpolate_onto_velocity_field()` function in `utilities.cc`.

**Comment by class4kayaker** [comment]
The current main time sink is in writing small classes so that the initial conditions can be used as Deal.II functions in the VectorTools::interpolate call. Using VectorFunctionFromScalarFunctionObject would require a bind to a virtual member function where, if this is actually possible, the method is not obvious.

I will probably have a WIP without the composition normalization logic up soon. Once this has been added, a possible further improvement would be to do some slight redesign to allow all of the composition interpolations to be done in a single call, though this would require some additional work as it isn't a duplication of the logic from VectorFunctionFromScalarFunctionObject.

**Comment by bangerth** [comment]
OK, good plan. Let me know if you have questions or need help about the adaptor classes.

**Comment by bangerth** [comment]
Fixed by #1144.
