### ISSUE TITLE
Getting deall.II and ASPECT to install without PETSc using CANDI

### ISSUE THREAD

**Issue by egpuckett** [geodynamics/aspect#1151]
This is related to Issue #1132. @hlokavarapu @spikebike, and I have found it VERY DIFFICULT to compile the deal.II libraries and the ASPECT binary on Ymir, which is a distributed cluster at UCD used by CIG researchers.  The basic issue is that deal.II has already been installed in a variety of places on the the machine. For example,

> ```
> /usr/local/lib/libdeal_II.so
> /usr/local/lib/libdeal_II.g.so
> /usr/share/apps/dealii-8.4.1/deal.II-v8.4.1/lib/libdeal_II.so
> /usr/share/apps/dealii-8.4.1/deal.II-v8.4.1/lib/libdeal_II.g.so
> /usr/share/apps/dealii-8.4.1/lib/libdeal_II.so
> /usr/share/apps/dealii-8.4.1/lib/libdeal_II.g.so
> /usr/share/apps/src/dealii-8.4.1/build5/lib/libdeal_II.so
> /usr/share/apps/src/dealii-8.4.1/build5/lib/libdeal_II.g.so
> /usr/share/apps/dealii-8.2.1/lib/libdeal_II.so
> /usr/share/apps/dealii-8.2.1/lib/libdeal_II.g.so
> ```

to list just a few of the places in the system deal.ii seems to be installed with PETSc.  (We can't remove PETSc from Ymir since some users are still using Citcom on it.)

The problem is that if we remove PETSc from

> candi.cfg

as follows

> PACKAGES="load:dealii-prepare"
> # PACKAGES="${PACKAGES} once:opencascade"
> # PACKAGES="${PACKAGES} once:parmetis"
> # PACKAGES="${PACKAGES} once:superlu_dist"
> 
> PACKAGES="${PACKAGES} once:hdf5"
> PACKAGES="${PACKAGES} once:p4est"
> PACKAGES="${PACKAGES} once:trilinos"
> # PACKAGES="${PACKAGES} once:petsc"
> # PACKAGES="${PACKAGES} once:slepc"
> 
> PACKAGES="${PACKAGES} dealii"

the candi install still finds PETSc somewhere else on Ymir and installs it in deal.ii, even though one would think the edits to candi.cfg would prevent this. 

The fix for this is to edit

> deal.II-toolchain/packages/dealii.package

and add

>  -D DEAL_II_WITH_SLEPC:BOOL=OFF \
> -D DEAL_II_WITH_PETSC:BOOL=OFF \

to

> CONFOPTS=" \
> ${DEAL_CONFOPTS} \
> -D CMAKE_BUILD_TYPE=DebugRelease \
>     .
>     .
>     .

But that is not all folks!

Now you need to build ASPECT in 

> aspect/build

with 

>  cmake -DDEAL_II_DIR=/home/egp/local/Code/deal.II-8.4.1/deal.II-v8.4.1 ..

i.e., explicitly specify the DEAL_II_DIR on the command line to cmake. Otherwise, it seems that cmake picks up one of the deal.II libraries already on the system; i.e.,

> ```
>  ./local/lib/libdeal_II.so
>  ./local/lib/libdeal_II.g.so
> ```

Furthermore, as far as I can tell, explicitly setting the environment variable DEAL_II_DIR, by executing

> source /home/egp/local/Code/deal.II-8.4.1/configuration/deal.II-v8.4.1

or 

> source /home/egp/local/Code/deal.II-8.4.1/configuration/enable.sh

etc., doesn't work. The cmake command in 

> aspect/build

namely,

> cmake ..

or something similar, still picks up the wrong deal.II.*.so.

My view is that there is a flaw in the logic of how candi finds both PETSc and the DEAL_II_DIR. One would think that by commenting PETSc and SLEPC out in 

> candi.cfg

e.g., 

> # PACKAGES="${PACKAGES} once:petsc"
> # PACKAGES="${PACKAGES} once:slepc"

then PETSc would be banished from the ASPECT binary that one subsequently makes. This is not true on a system (at least our Ubuntu system) that has PETSc and deal.ii already installed in

>  /usr/local/lib 

or the equivalent.

**Comment by bangerth** [comment]
As a general rule, if a package is installed on a system in a central location, it is almost always the wrong thing to not use it and instead build a replacement in a user directory. This is, for example, why it creates no end of trouble if people install PETSc with the `--download-mpich` flag.

In other words, I think that candi is doing the right thing choosing the PETSc that is already installed on the system. If that PETSc version is somehow defective, then it either (i) needs to be replaced, or (ii) one has to explicitly specify a different one somewhere. The same argument can be made for your local ASPECT picking up the deal.II version from `/usr/local`: if that is not the deal.II version to be used, then it either (i) needs to be replaced, or (ii) one has to explicitly specify a different one somewhere.

Concretely, in your case: Why *don't* you want to use the globally installed version of deal.II? Just because it has been installed against PETSc is not a problem. It just has to *also* be installed against Trilinos, but these things are not mutually exclusive.

**Comment by egpuckett** [comment]
@aaronistheman may be interested in this issue.

**Comment by bangerth** [comment]
Any news on this, or can we close it?
