### ISSUE TITLE
Visualization output of error indicator is expensive

### ISSUE THREAD

**Issue by spco** [geodynamics/aspect#1252]
I'm playing around with the `error indicator` visualization, and have hit a snag. I want to visualize the primary variables of the solution at every timestep, but I only refine every `n` timesteps. I'm only really interested in seeing the error indicators in play every time I refine, but the way `postprocess/visualization/error_indicator.cc` is implemented actually means I am having to *calculate* the error indicator every single timestep. This is hugely expensive, taking up 50% of my computation on the shell_simple_2d cookbook (with dG temperature and a different error indicator). I'd value your thoughts on the following avenues, in case there is any useful discussion to be had.

1) Is there some way I can output *only some* variables depending on the timestep? I suspect not, and it's probably not a good solution - Paraview or Visit will have a fit if some timesteps lack a field.

2)  Should we keep the error indicators hanging around from the previous adaptive timestep? The latter is difficult since the mesh will have changed, and would require some interpolation or projection, besides the memory issues.

3) Should the visualization output mechanism in `postprocess/visualization/error_indicator.cc` be tweaked to output zeros on non-adaptive timesteps?

4) Is there a case for some mechanism a la option 3 but more global, rather than ad hoc for this one case? There could be other cases where output is only wanted for some fields at some timesteps, but I think this could easily turn out to fit nobody's needs in a nice way.

5) Should I just modify my error indicator so it outputs zeros if it's not an adaptive timestep? This is easy, cheap and dirty, but is there a better and more extensible way?

Feel free to tell me just to do 5 and move on :)

**Comment by tjhei** [comment]
> This is hugely expensive, taking up 50% of my computation on the shell_simple_2d cookbook

In release mode? Is the cost because of the error computation or because you are doing more IO (you could check by just outputting 0 as the values)? Does the performance really matter for such a simple problem?

> 1) Is there some way I can output only some variables depending on the timestep?

No, I don't think that would work (paraview/visit would likely complain).

> 5) Should I just modify my error indicator so it outputs zeros if it's not an adaptive timestep? This is easy, cheap and dirty, but is there a better and more extensible way?

You really want to look at the indicators right before the refinement takes place and not after, right? That makes it a bit more difficult to detect in the code. Adding an option to only run error computation on refinement sounds like the best option (and outputting 0 otherwise).

**Comment by spco** [comment]
> Is the cost because of the error computation or because you are doing more IO (you could check by just outputting 0 as the values)? Does the performance really matter for such a simple problem?

It's the error computation. It's quite annoying to have it doubling my computational cost.

> You really want to look at the indicators right before the refinement takes place and not after, right? That makes it a bit more difficult to detect in the code

Sure. At least the output occurs before refinement, or I'd really be screwed ;)

I think the right thing is just to output zeroes the rest of the time. I'm happy to have that just as a tweak to my own code, and let others worry about it if they have the same issue with their indicators (if anybody else visualises them at all!).

**Comment by gassmoeller** [comment]
I sometimes do, but I never noticed such a dramatic slow down. Do you use an especially expensive refinement indicator?

**Comment by spco** [comment]
Fairly expensive (involves a global mass matrix inversion plus lots of `FEFaceValues.reinit`s), but I am also outputting visualization at every timestep, so the combination starts to add up. If I just calculate it at each adaptivity timestep it's only 3-4%.

**Comment by gassmoeller** [comment]
Ah, I see. I guess then it makes sense to change your visualization output to only output it every adaptivity step, and output 0 otherwise. As far as I know we currently have no such expensive refinement indicator in the master branch, so I do not think it is necessary to include this option there (unless somebody else has made the same experience with a different refinement indicator).

**Comment by spco** [comment]
Yeah, that's what I'm guessing. Thanks for the sounding board!

**Comment by bangerth** [comment]
Good we talked about it ;-)
