### ISSUE TITLE
Remove MaterialModel::InterfaceCompatibility

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#1538]
This involves deriving MaterialModel's from ``MaterialModel::Interface`` instead of ``MaterialModel::InterfaceCompatibility`` and implementing ``evaluate``:
- [x] convert tests
- [x] convert benchmarks/cookbooks
- [x] remove class

**Comment by bangerth** [comment]
@alarshi -- can you list here the numbers of the pull requests you wrote that make this conversion? I see #1706, #1700, #1699. Did I miss any?

We like to keep track which pull requests address which issue. Ideally, pull requests list the issues they address so that github can keep track of these connections.

**Comment by gassmoeller** [comment]
Resolved in a whole bunch of pull requests by @alarshi. Thanks!

**Comment by bangerth** [comment]
Yay!
