### ISSUE TITLE
Advertise candi as default installer?

### ISSUE THREAD

**Issue by gassmoeller** [geodynamics/aspect#1818]
Our local installation section in the manual is out of date (e.g. it recommends deal.II 8.4, which is not longer supported), and while I am willing to rewrite that section I thought it is also time to discuss if we should advertise candi (https://github.com/dealii/candi) as the new default installer. 

As far as I know @tjhei , @egpuckett and @hlokavarapu use candi already for different purposes, and I have started to use it as well (also for cluster installations). While it requires one more configuration step (and therefore one more level of possible problems) it avoids a lot of the usual installation problems like inconsistent compilers between different packages. Additionally, it would allow us to ship different 'platform' files with ASPECT that contain configurations that are known to work on some clusters (e.g. stampede).

I am imagining that we could use candi to make a full ASPECT installation for most usual desktop systems as simple as:
```
git clone https://github.com/dealii/candi.git
cd candi
candi.sh -j8 -p /path/to/install --packages="load:dealii-prepare once:p4est once:trilinos once:dealii aspect"
```

Is this something worth pursuing? I have spent far too much time helping with installation problems, and it would be nice to at least only solve these problems once, incorporate the improvements in candi, and then never think about them again.

**Comment by bangerth** [comment]
Yes!

**Comment by tjhei** [comment]
In general: yes. The more people use candi, the more robust it will become. Manual installation of packages is just too tedious.

If you specify the packages manually (as you do above), do you still get the packages that the platform requires?

Regarding an ``aspect`` package inside candi: I am not sure if this is the easiest way to go, because most of us want to develop with aspect, so the directories would be /path/to/install/tmp/unpack/aspect and /path/to/install/tmp/build/aspect are somewhat annoying.

Would it be that much harder to say: "now get/configure/build aspect by
```
source /path/to/install/configuration/enable.sh
git clone https://...
cd aspect
mkdir build && cd build
cmake ..
make
```
"?

**Comment by gassmoeller** [comment]
You are right the suggestion above overwrites config files. Lets postpone that idea then, and simply use candi to install deal.II. I have rewritten the install instructions in #1821, and will close this issue for now, as it seems we generally agree on using candi.
