### ISSUE TITLE
how to set temperature pre-factor for the viscosity formula in 'simple' Material model

### ISSUE THREAD

**Issue by Lydia823** [geodynamics/aspect#1917]
In the part A.78 Parameters in section Material model of manual, there is a model 'simple' in page 314.
What is value 'x' mean in H(x) of the temperature pre-factor for the viscosity formula ? And how to set x in 'Simple model'?

**Comment by jdannberg** [comment]
Dear @Lydia823, 
if you have a general question such as this one, please ask it on the ASPECT mailing list (see [this webpage](http://lists.geodynamics.org/cgi-bin/mailman/listinfo/aspect-devel)). We use the github issues to track bugs/problems in the code, so I will close this issue for now. 

To answer your question, the x is just the argument that is used to explain what the function H does, so you don't have to set it in the input file. The equation you are referring to just says that if the argument of the function H (which is the term on the left part of the page, `exp(-beta(T-T0)/T0)`) is smaller than a minimum value tau_min, or larger than a maximum value tau_max, it will be cut off at these values, and otherwise it will be used in this form to compute the temperature dependence of the viscosity. You can specify tau_min, tau_max, beta and T0 in the input file as described in the paragraph following the equation.

**Comment by Lydia823** [comment]
Thanks a lot.@jdannberg
