### ISSUE TITLE
optional simplified adiabatic heating

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#209]
We are using total pressure instead of static pressure for the adiabatic heating term. This is in contrast to other codes, so it might be a good idea to supply an option that allows the user to decide what she wants. See #207.

**Comment by gassmoeller** [comment]
Ok now we ran into the case in which we actually want to change the shear heating formulation as well (due to some complicated physics involving different deformation mechanism that contribute to viscosity). Therefore, we would like to use a different viscosity for the shear heating than for the stokes system. Currently, the only way would be to change the assembly. Maybe we can think about a formalism to allow for more flexible heating mechanisms at the hackathon?

**Comment by bangerth** [comment]
It seems thermodynamically inconsistent to use different viscosities. Can you elaborate what these models attempt to achieve?

**Comment by gassmoeller** [comment]
Well, I can try. The current implementation assumes that all of the deformation work that is done is converted to thermal energy in the form of shear heating. In the model we try to set up a part of this work is actually used to decrease the grain size (increasing the surface energy of the system). So what we actually want to do is multiply the shear heating by (1-surface_area_work_fraction), which changes in dependence of the solution. We can calculate this factor in the material model, but we need a way to use it for the shear heating (e.g. By modifying the current formulation or by providing a way to select a different heating term).

**Comment by bangerth** [comment]
Hm, if I understand correctly then what is really happening here is that you convert mechanical energy (shear friction) into not just heat but in fact heat + chemical energy (in the form of crystal breakage)? If so, can't you just model this by first converting everything into heat, but then have another *heat sink* term coming from your material model that is proportional to the amount of energy that is converted into chemical energy? That would seem like a cleaner way to do it, given that we already have the ability to treat such terms (I believe).

**Comment by jdannberg** [comment]
Yes, you are correct, we want to convert a fraction of the mechanical energy into not just heat, but a different kind of energy (grain boundary energy - energy is minimised when the surface area of the grains is small, i.e. when there is one big crystal instead of several smaller ones). 
A heat sink would be a way to implement this, but the way the heating model is implemented right now, it is not in the material model, but in a different plugin, and it does not even get the material model inputs and outputs. But it would be a great idea to either have the option to have such an additional heating term in the material model, or put all of the heating terms out of the assembly and into a separate heating model, which would then get the material model inputs and outputs.

**Comment by bangerth** [comment]
Would what you want to do be possible now with your implementation in #416?

**Comment by jdannberg** [comment]
Yes. Closed by #416.
