### ISSUE TITLE
Diffusion Formulation Bug in Visco plastic material model

### ISSUE THREAD

**Issue by sibiaoliu** [geodynamics/aspect#2123]
Hi there,

I am running the intraplate compression model with visco-plastic material model.  Since I add both the diffusion and dislocation rheology, I found two questions.
1. The formulation of the diffusion creep viscosity is wrong: 
In visco_plastic.cc, Line 198, `// viscosity = 0.5 * A^(-1/n) * edot_ii^((1-n)/n) * d^(m/n) * exp((E +...`,   it should be **d^(-m/n)** if the grain size `d` is 1 mm (i.e., the default value in the code).

So, in Line 205, the equation should be `double viscosity_diffusion =...std::pow(grain_size, -grain_size_exponents_diffusion[j]);`. Another way is to `set Grain size = 1000` in the Input file. This is what I am doing now. It's a tiny error about missing the minus sign, but will make the viscosity value wrong :smile: 

2. As I am focusing on the lithosphere-upper mantle scale simulation, it is better to use the composite creep viscosity in each individual composition phase. It is not necessary, however, to add the diffusion creep to the crust. I am wondering that is it possible to set the diffusion parameters for only the lithospheric mantle and upper mantle?  For example, can I only set 3 values of diffusion parameters rather than 6 values if I have 5 compositional fields?  How about  `set Prefactors for diffusion creep =  1.e3, 1.e3, 1.e3`

By the way, just a remind: the current version of aspect seems to not work on the XCode version >9.0 on Mac OS, due to the missing SDK file "MacOSX10.12.sdk".

Thank you very much!

**Comment by naliboff** [comment]
@sibiaoliu - Thanks for the questions! 

First, a quick note. The equations you refer to in `visco_plastic` model have been updated slightly since the last release. Are you using version 1.5? For reference, the current version can be seen here: [visco_plastic](https://github.com/geodynamics/aspect/blob/master/source/material_model/visco_plastic.cc) 

Question 1 - I am a bit confused as to why the equation would need to be altered to have `A^(-1/m)`. The current formulation looks correct. If one were to define the strain rate for diffusion creep, rather than viscosity, the equation would contain `A^(-1/m)`.

Question 2 - Yes, the current composition option is not particularly helpful if one does not want to use a composite viscosity in all the material models. A quick solution is to change the composite viscosity formulation to:
`std::pow( 1.0/viscosity_diffusion + 1.0/viscosity_dislocation, -1.0 )`
In the crustal layer, you can then set the diffusion viscosity terms to give you a value of 1. If you think this will be useful for other users, I can add an option to select between the two composite viscosity formulations. I've seen both formulations used in the literature. In future material models the plan is to allow users to select whether the viscosity of each compositional field uses the diffusion, dislocation or composite option.

Question 3 - Are you running on the latest Mac OSX release. A number of users have successfully installed ASPECT and all the dependencies from scratch (e.g., not with the pre-built deal.II version) using compilers (openmpi, c/c++, etc) installed via Fink. That seems to be the option at the moment.

**Comment by sibiaoliu** [comment]
@naliboff - Thanks for the answering.

Yes, I am now using version 1.5. 

Q1: I mean the term of grain size `d^(m/n)`, rather than `A^(-1/n)`.  m is the grain size exponent, n is the stress exponent. For the prefactor A, it is correct. 
For the diffusion viscosity, it should be: `eta = 0.5 * A^(-1/n) * 1/d^(m/n) * exp((E+pV)/RT)` (Say Equation 1) since n = 1. However the current formulation is  `eta = 0.5 * A^(-1/n) * d^(m/n) * exp((E+pV)/RT)` (Say Equation 2)
If the grain size `d = 1e-3, m = 3` (default),  then the diffusion viscosity in the current formulation (from Equation 1) will be 18 orders of magnitude smaller than real one (from Equation 2). 

Q2: Thanks for the solution! That's would be great if you can add the opition in the future material models.

Q3: I am running on OS Sierra, not on High Sierra.  There are no problems for me to intall and use compilers. I also re-installed the latest ASPECT successfully by reducing the version 9.2 of XCode to the version 8.0. Just in case, some new users may meet the problem of SDK file missing during the installation.

**Comment by naliboff** [comment]
@sibiaoliu  

Q1: Sorry, I meant to write `d^(m/n)` verse `d^(-m/n)`. First cup of coffee and all that. Aside, I have always seen the equation written as `eta = 0.5 * A^(-1/n) * d^(m/n) * exp((E+pV)/nRT)`. Can you point me to the reference using the `1/d^(m/n)` term in the viscosity equation?

Q2: Sure thing and let me know if you would like that option incorporated in the main branch or if you are happy to just use it in your local branch. We have not been adding small updates like that to the material as at some point the code gets overwhelmed with very specific additions.

Q3: Gotcha, thanks for the heads up. This note could get added to the deal.II wiki with installation instructions for installing Mac OSX.

**Comment by sibiaoliu** [comment]
@naliboff 

Q1: Sure, one good reference would be the book: Introduction to Numerical Geodynamic Modelling by T. Gerya, 2010. page 75-80. Specifically, the equation 6.5b, 6.10 (axial compression), and 6.15 (simple shear). What I used the grain size before is 1e3 meter instead of 1e-3 meter in the current formulation.

Q2: I prefer to use the local branch for testing since it is small changing. Additionally, I may add some other minor changes to the specific case of my model. 

Thanks again.

**Comment by naliboff** [comment]
Q1 - Interesting. All of the current material models in ASPECT use the form of the equation outlined in visco_plastic and most other papers I am familiar with do as well.  

@jdannberg @gassmoeller - Have you come across this alternate viscosity formulation for the grain size term?

**Comment by jdannberg** [comment]
I think I know what's going on. Taras defines his m differently from what most other people do. If you read the whole paragraph, his m is negative, so m ~ -3 for diffusion creep, while most other people (including our implementation in ASPECT) define m as positive. So that's where the minus sign comes from. 

If you look for example at equation (5) in Becker, T. W. (2006) On the effect of temperature and strain-rate dependent viscosity on global mantle flow, net rotation, and plate-driving forces. Geophysical Journal International, 167(2), 943-957 [(here)](https://doi.org/10.1111/j.1365-246X.2006.03172.x) you see that there the equation is the same as we have implemented it, with the term d^(m/n). In Taras Gerya's book, his prefactor also has a different unit because of that: A_D is in Pa^(−n) s^(−1) m^(−m), instead of Pa^(−n) s^(−1) m^(m) as in Thorsten Becker's paper. 

So our implementation in ASPECT is correct, it just uses a different convention. You have to use a positive instead of a negative m.  The larger the grains, the higher the viscosity.

**Comment by jdannberg** [comment]
Oh and about your second question: 
Why don't you just set the diffusion creep prefactor to a very small value in the crust such that the diffusion viscosity in the crust becomes very large, and is essentially only used if the strain rate is almost 0? Is that not the behaviour you want? It might be useful to have that in any case, so that you viscosity doesn't just go to really high values in case you have a zero strain rate...

**Comment by sibiaoliu** [comment]
@jdannberg - Thanks Juliane!

Q1: So the formulation is correct and the key point is the value of the prefactor A with the unit: Pa^−1 * m^(1/m) *s−1 for the diffusion creep. The value from other reference paper should be very carefully and converted to the right value in ASPECT. (I will also check my A value for dislocation creep :) 

Q2:  Gotcha.  That's exactly what I want!



**Comment by jdannberg** [comment]
@sibiaoliu 

Q1: I guess the key point is the value of m. It is positive in ASPECT, but negative in Taras' book. I guess for every reference you use, you have to check if they use the same or a different formulation compared to what we do. But most papers I've seen use the on in ASPECT (the one from Thorsten Becker's paper). 

Q2: Perfect!

**Comment by sibiaoliu** [comment]
@jdannberg 

Q1: To the end, if the unit of A in ASPECT is the same as `Pa^−n * m^(m) *s−1` in T. Becker's paper , then the unit of `Prefactors for dislocation/diffusion creep` should be corrected in the manual (Pa^−n * m^(n/m) *s−1)?

**Comment by jdannberg** [comment]
The example I gave was for diffusion creep (n=1). In general, (Pa^−n * m^(n/m) *s−1) should be correct.

**Comment by jdannberg** [comment]
Oh, wait, I see. You mean it should be `m^(m)` instead of `m^(1/m)`?

**Comment by sibiaoliu** [comment]
Exactly :)

**Comment by jdannberg** [comment]
@naliboff, does that seem right to you? The unit should be `$Pa^{-1} m^{m_{diffusion}} s^{-1}$` for the Prefactors for diffusion creep, and `$Pa^{-n_\\text{dislocation}} s^{-1}$` for the Prefactors for dislocation creep, correct? So we should update that in the documentation of all the material models that use this law?

**Comment by naliboff** [comment]
@dannberg - Yep, the units above look right to me.  @sibiaoliu - Nice catch on the documentation of `A`! I'll submit a pull request with the change in a little bit.

**Comment by jdannberg** [comment]
Great, thank you!
:+1:
