### ISSUE TITLE
2D section view in 3D model

### ISSUE THREAD

**Issue by cgw0814** [geodynamics/aspect#2216]
Hi, all, how could I get 2D section profile of any directions in 3D extensional model, For example, as figures
![2018-05-06 9 30 01](https://user-images.githubusercontent.com/38973778/39673755-adb7d830-5174-11e8-89df-d8f1c15c57d2.png)
![2018-05-06 9 29 35](https://user-images.githubusercontent.com/38973778/39673756-adef1cbe-5174-11e8-8944-3732789d81d5.png)

**Comment by MFraters** [comment]
Hey,
Welcome to ASPECT! ASPECT can produce different output formats such as vtu/vtk and gnuplot. For more info see the manual (http://www.math.clemson.edu/~heister/manual.pdf#subsection.5.76), under the variable `Output format`. You can then visualize the data in several programs such as paraview or VisIt in which you can make these kind of cross sections of the 3d data.

**Comment by jdannberg** [comment]
@cgw0814, did this answer your question? Usually, the place to ask questions like this would be the [aspect mailing list](https://lists.geodynamics.org/cgi-bin/mailman/listinfo/aspect-devel), while the issues on github help the developers to keep track of bugs we have to fix or missing features. So I'll close this issue here.
