### ISSUE TITLE
Improve AMG for variable viscosity

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#237]
As shown in issue #234 we don't currently do a particularly good job preconditioning the A block of the matrix. The approach to do better is discussed in May & Moresi, PEPI 171, pp. 33-47. It would just have to be implemented :-)

**Comment by bangerth** [comment]
I read through the paper by May and Moresi and it addresses a different question (at least that's my take-away message): what best to do to precondition the Schur complement (we just use a scaled mass matrix). This is an issue that pertains to the number of outer iterations, whereas doing something about how well AMG solves the top left block is something that primarily pertains to inner iterations.

Of course, we should address both issues -- I have testcases that demonstrate that each of the two can be a problem.

**Comment by jedbrown** [comment]
Our experience has been that the advantage of the LSC preconditioner in May & Moresi is specific to the unstable (Q1-P0) discretization used by Underworld. With a stable discretization like Q2-P1, the scaled mass matrix has performed better. As for solving the viscous block using AMG, you can do it with GAMG or ML, but you need to provide the rigid body modes and setup will be expensive. And with the Q2 discretization, performance tends to be very sensitive to thresholding because the unthresholded graph would coarsen much too fast. Our SC14 paper demonstrates that there is a very large benefit to geometric coarsening and to the use of matrix-free methods on the finest level(s).

**Comment by bangerth** [comment]
@jedbrown : Thanks for the insight. We do provide the rigid body modes to ML. I'm not so much worried about the cost of setup -- we seem to have cases where ML just turns out to be a not very good preconditioner at all for the top left block (of course these are exactly the cases with strongly varying viscosity), and that I wanted to improve.

I am ready to believe that geometric multigrid is very useful, but we don't currently have the software infrastructure to make that happen in parallel :-(

**Comment by tjhei** [comment]
> I am ready to believe that geometric multigrid is very useful, but we don't currently have the software infrastructure to make that happen in parallel :-(

"soon" :-)

One way to cheat might be to apply some kind of averaging of the viscosity inside each cell.

**Comment by bangerth** [comment]
The averaging has been implemented and vastly improves the situation. See the manual section committed as part of #306.
