### ISSUE TITLE
citing.html: Some other cleanup questions

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#2628]
Now that #2622, #2597 and #2594 are all in, https://aspect.geodynamics.org/citing.html looks substantially nicer I believe. What's not clear to me is what the (now green) box at the top is supposed to do. Why would anyone need to know a link to the page with its selection?

**Comment by jdannberg** [comment]
> Now that #2622, #2597 and #2594 are all in, https://aspect.geodynamics.org/citing.html looks substantially nicer I believe.

I have to say I find the contrast between the red and green a bit too much, so if you're okay with that, I would change it back to a darker colour (it doesn't matter to me if it's green or blue). 

> What's not clear to me is what the (now green) box at the top is supposed to do. Why would anyone need to know a link to the page with its selection?

You mean the red box?
I am not sure, but I agree, if there's no good reason to have it, it will just confuse people, and even if we decide we need it, maybe we can at least move it to the bottom so that people see the more important things first?

**Comment by bangerth** [comment]
On 08/23/2018 02:50 AM, Juliane Dannberg wrote:
>     Now that #2622 <https://github.com/geodynamics/aspect/pull/2622>, #2597
>     <https://github.com/geodynamics/aspect/pull/2597> and #2594
>     <https://github.com/geodynamics/aspect/pull/2594> are all in,
>     https://aspect.geodynamics.org/citing.html looks substantially nicer I
>     believe.
> 
> I have to say I find the contrast between the red and green a bit too much, so 
> if you're okay with that, I would change it back to a darker colour (it 
> doesn't matter to me if it's green or blue).

There's only one green box left now. Does that work for you?

**Comment by jdannberg** [comment]
Yes. I already changed the colour and @tjhei merged it :grinning:
