### ISSUE TITLE
Error in solution.xdmf file when simulation resumes from restart files

### ISSUE THREAD

**Issue by ricitron** [geodynamics/aspect#2797]
Hello,

I noticed a strange error that appears in the solution.xdmf file when I restart an ASPECT simulation. The error only occurs when a simulation stops and then is resumed from the restart files. If a simulation completes in one go then the solution.xdmf file is fine.

When I start the simulation, the solution.xdmf file begins:

```
<?xml version="1.0" ?>
<!DOCTYPE Xdmf SYSTEM "Xdmf.dtd" []>
<Xdmf Version="2.0">
  <Domain>
    <Grid Name="CellTime" GridType="Collection" CollectionType="Temporal">
      <Grid Name="mesh" GridType="Uniform">
        <Time Value="0"/>
        <Geometry GeometryType="XY">
          <DataItem Dimensions="1769472 2" NumberType="Float" Precision="8" Format="HDF">
            solution/mesh-00000.h5:/nodes
          </DataItem>
```

However, when the simulation stops and then I resume it from the restart files, the solution.xdmf file is changed so it appears:

```
<?xml version="1.0" ?>
<!DOCTYPE Xdmf SYSTEM "Xdmf.dtd" []>
<Xdmf Version="2.0">
  <Domain>
    <Grid Name="CellTime" GridType="Collection" CollectionType="Temporal">
      <Grid Name="mesh" GridType="Uniform">
        <Time Value="0"/>
        <Geometry GeometryType="XYZ">
          <DataItem Dimensions="1769472 4294967295" NumberType="Float" Precision="8" Format="HDF">
            solution/mesh-00000.h5:/nodes
          </DataItem>
        </Geometry>
```

Any line that previously had ' <DataItem Dimensions="1769472 2" ...' now has '<DataItem Dimensions="1769472 4294967295" ...'. All the number '2' values are replaced with '4294967295' after the simulation is restarted from the restart files. 

This only occurs when I restart the simulation from the restart files. I noticed this on two clusters I had the software installed on, and a completely different user tested this with a different install on a different cluster and noticed the same error. 

Because of the error in the solution.xdmf file, I cannot load the data into Paraview. However, if I find and replace '4294967295' with '2' then I can load the .xdmf file into paraview just fine. It appears that everything else in the .xdmf file is fine except for this strange error. 

Thanks.

**Comment by gassmoeller** [comment]
Hi Robert,
that looks like an interesting issue, thanks for reporting. Just to be sure: You did not accidentally change the dimension between you checkpointed model, and the restarted model (e.g. by accidentally restarting from a wrong output folder)? If not, then we will need to look into the serialization of the source/postprocess/visualization postprocessor, and in particular the `xdmf_entries` variable. Let me know once you have checked the first part.

**Comment by ricitron** [comment]
Hello Rene,
I don't change the input file at all between restarting. The input file has 'set Resume computation = auto' so to restart I just run the same input file in the exact same way as I did when I started the simulation.

**Comment by gassmoeller** [comment]
Hi Robert,
I could reproduce your problem and found the corresponding issue in deal.II. It was really just a one line change to fix it (and I was the one who introduced the bug in the first place a year ago). I proposed the fix in dealii/dealii#7691. Unfortunately, since this is a fix in deal.II (the earliest release that will get it is 9.1.0) it will take a while until we can require this new deal.II version for ASPECT. 
If you need this urgently you have two options:
1. Update deal.II and ASPECT to the newest development versions (deal.II to get the fix, and ASPECT because only the newest ASPECT version works with deal.II dev, see #2602).
2. Do the fix yourself in your current deal.II version. It is just a single word fix in include/deal.II/base/data_out_base.h as you can see in dealii/dealii#7691. Then recompile and install the modified deal.II and recompile your current ASPECT and everything should work as expected.

Let me know if that works, and close this issue if it works for you.

**Comment by ricitron** [comment]
Thanks Rene, that works! Thanks a ton for finding the issue in deal.II and correcting it.

**Comment by gassmoeller** [comment]
Just for future reference until we require deal.II 9.1.0: Broken .xdmf files can be fixed with the following shell command, where 'DIM' needs to be replaced by the dimension of the model (2 or 3):
```
sed -e 's/4294967295/DIM/g' solution.xdmf > solution_fixed.xdmf
```
