### ISSUE TITLE
rotational modes in 3d broken

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#304]
Nullspace removal doesn't work in 3d with hanging nodes. Reported by Scott.

Here is an example file: https://github.com/tjhei/aspect/blob/net_rot_broken/net_rot_broken.prm

**Comment by tjhei** [comment]
I added some diagnostics and also commited some example output to [1].

This is what happens if I repeat the nullspace removal on a globally refined mesh:
```
removing nullspace 0 with power 1.3568e-05
removing nullspace power after -1.41878e-20
removing nullspace 1 with power 5.3328e-06
removing nullspace power after -6.45863e-21
removing nullspace 2 with power -3.72324e-05
removing nullspace power after 7.49624e-20
removing nullspace 0 with power -1.05879e-20
removing nullspace power after -6.35275e-22
removing nullspace 1 with power -7.19978e-21
removing nullspace power after 1.05879e-22
removing nullspace 2 with power 7.45389e-20
removing nullspace power after 0
```
and this is the output with hanging nodes:
```
removing nullspace 0 with power 0.0116733
removing nullspace power after 2.05998e-17
removing nullspace 1 with power -0.0252177
removing nullspace power after 3.20653e-17
removing nullspace 2 with power -0.0042168
removing nullspace power after 4.75016e-18
removing nullspace 0 with power -0.00250944
removing nullspace power after 2.20906e-18
removing nullspace 1 with power 0.000205563
removing nullspace power after -1.14349e-19
removing nullspace 2 with power -0.000120724
removing nullspace power after -7.6233e-20
```
I wondered if it because of the constraints and modified the code to use 0 in constrained entries (see [2]), but that doesn't help:
```
removing nullspace 0 with power 0.0100247
removing nullspace power after -2.71051e-17
removing nullspace 1 with power -0.021333
removing nullspace power after 3.4437e-17
removing nullspace 2 with power -0.00357855
removing nullspace power after 2.85958e-18
removing nullspace 0 with power -0.00222494
removing nullspace power after 3.49825e-18
removing nullspace 1 with power 0.000158938
removing nullspace power after -3.39237e-19
removing nullspace 2 with power -9.57672e-05
removing nullspace power after 9.76205e-20
```

@ian-r-rose, @bangerth : any ideas? I am giving up for now.

[1]: https://github.com/tjhei/aspect/tree/net_rot_broken
[2]: https://github.com/tjhei/aspect/commit/e80e6bb5e7f1694a4d292e423d438ac170381ef5

**Comment by ian-r-rose** [comment]
I think I see the problem.  Basically, the way we are calculating the power in the nullspace modes (line 168 in nullspace.cc) is simply not correct.  Instead of dotting the two vectors, we should be integrating the inner product of the two over the domain.  Dotting the two vectors does not correctly weight the degrees of freedom by their effective volumes in the domain.

For sufficiently uniform meshes, the way it currently is implemented seems to be good enough.  However, it is not good enough when there is adaptive refinement.

I would note that this is also a good opportunity to implement some of the unfinished functions in nullspace.cc

I can fix this, but it is not a quick fix, so I won't be able to get to it for a few days, I think...

**Comment by bangerth** [comment]
I think it would be useful to spell out in formulas what all of the functions in this file should do. I'm trying to read through it, but I'm actually not sure whether the code is right or wrong in basically the entire file -- and that suggests that what is really missing is a specification of what the code is supposed to do.

Take removing the rotation as an example: given a vector field $u(x)$, we'd like to remove rotation around the $z$ axis. (And, possibly, similar for the other axes.) The net rotation is given by
$$
  R_z(u) = int_\Omega  (u \times e_z) cdot x  dx = int_\Omega  (e_z \times x) cdot u  dx 
$$
(I believe, we may debate this, the point simply is that having a specification would be useful). This can be expanded into the elements of the finite element basis as forming the dot product
$$
  R_z(u) = b \cdot U
$$
where
$$
  b_j = \int\Omega   (e_z \times x) cdot \varphi_j  dx.
$$
Then we seek a vector field $u_r$ to add so that $R_z(u-u_r)=0$. We will choose $u_r$ so that it is proportional to $e_z \times x$ and get that we need
$$
  u_r = ... b
$$
(too lazy to compute the factor for now). 

I think if we write down the exact formulas the code will write itself, and be correct.

**Comment by ian-r-rose** [comment]
You are absolutely right that the specific formulae should be better documented.  I have them on a piece of paper in front of me, but have not typed them up.

I do think that what I have submitted in #305 does what you describe, where there are two flavors: (1) R_z includes density, and can be interpreted as "net angular momentum" and (2) R_z does not include density, and can be interpreted as a "net rotation".

As it currently stands, however, I do not explicitly calculate b_j, as it would need to be re-evaluated at every timestep anyways, at least for the "momentum" case. (I think, at least)

**Comment by bangerth** [comment]
Yes, whether you store b_j or not isn't all that important. The point is that you need it twice, once for computing the rotation, and then for subtracting it. You don't need to store it in between these two steps (one can compute it on the fly every time).

Would you mind adding the formulas you use to the documentation of the function? Either as part of the code, or as separate function documentation. I think this would actually be very helpful to evaluate what the code is supposed to do, and to evaluate what it actually does.

**Comment by ian-r-rose** [comment]
Yes, I am working on adding some documentation to parameters.cc right now, though the manual build scripts are acting up on my system, so I will have a hard time checking on the typesetting.

**Comment by bangerth** [comment]
No worries about that, we'll catch it during review if necessary. Also: thanks a lot!

**Comment by ian-r-rose** [comment]
Okay, I've added some documentation to the remove nullspace portion of the manual.  Feedback appreciated, of course.

**Comment by bangerth** [comment]
> I think I see the problem. Basically, the way we are calculating the power in
> the nullspace modes (line 168 in nullspace.cc) is simply not correct. Instead
> of dotting the two vectors, we should be integrating the inner product of the
> two over the domain. Dotting the two vectors does not correctly weight the
> degrees of freedom by their effective volumes in the domain.

Yes, that is entirely correct. The formula you cite is not wrong, but it has 
to be interpreted as the dot product in function spaces, not on finite 
dimensional vectors.

**Comment by bangerth** [comment]
Is this fixed now by #305?

**Comment by ian-r-rose** [comment]
It should be.  At least, the parameter file that Timo posted works on my system.  It would be nice to get confirmation on that, though.

**Comment by tjhei** [comment]
Yes.
