### ISSUE TITLE
How large the used memory increases when using larger "GMRES solver restart length"

### ISSUE THREAD

**Issue by Shangxin-Liu** [geodynamics/aspect#3288]
Hi,

Just wonder does anyone have a sense of how large the used memory increases when I use larger "GMRES solver restart length"?

For example, for the previous default value of 50 for Stokes "GMRES solver restart length", I will not exceed the upper limit of 120,000 DOFs per GM RAM on our cluster. Now if I increase the Stokes "GMRES solver restart length" to 200, how large the used RAM will increase? Does anyone have a sense of this trend? I'd like to be conservative on our computing resources for my large models.

And also for the advection "GMRES solver restart length",  any general guide on the memory increase trend with larger values? 

Maybe Rene or Juliane can provide some advice on this?      @gassmoeller         @jdannberg 

Best,
Shangxin

**Comment by gassmoeller** [comment]
Hi Shangxin,
increasing the GMRES solver restart length will increase the memory that the GMRES solver needs linearly (so x2 will need x2 as much memory), however in most computations the system matrix is bigger than the  GMRES solver (unless you use the new GMG preconditioner that does not need a matrix for the Stokes system). You can check the individual memory needs with the 'memory statistics' and/or 'matrix statistics' postprocessors (I do not think the GMRES solver appears there except in the total memory consumption). However, keep in mind the GMRES solver becomes slower for very high restart length (quadratically), so only increase the restart length if you have convergence problems, otherwise it is often not helpful.

**Comment by tjhei** [comment]
What Rene says is correct. What @tcclevenger found is that it seems like that with a restart length of less than about 150 the quadratic nature of the cost of GMRES is not yet visible for typical problems.

@tcclevenger can give additional information here.

**Comment by tcclevenger** [comment]
For the Stokes solve, @gassmoeller  is correct, the largest consumer of memory should be the system and preconditioner matrices when there is a restart length less than 100. Over this, the temporary vectors inside GMRES become the largest memory consumer for the Stokes part.  

A GMRES restart length of 100 is almost indistinguishable in cost from a GMRES restart length of 50 (the default for Stokes in ASPECT), and like @tjhei said, only around 150 does it become noticeable (and around 200 does it become significant).

I would not recommend going higher than 150 if you still see convergence.

**Comment by gassmoeller** [comment]
I think this was answered, feel free to reopen if I am mistaken.
