### ISSUE TITLE
Could not successfully load shared library <> : No such file or directory

### ISSUE THREAD

**Issue by XieJChris** [geodynamics/aspect#3526]
Recently I wrote a .cc file and compile it successfully, but there was a problem when I ran the .prm file, and then I tried to run other files in other folders (like, /aspect/cookbooks/finite_strain/finite_strain.prm), but I still got the same problem as before, so guys, any suggestions?

**Comment by naliboff** [comment]
@XieJChris - Can you post the error message obtained when running the finite strain benchmark? Likewise, please post the line in the parameter file that points to the finite strain plugin? Thanks!

**Comment by tjhei** [comment]
Can you also please post your "detailed.log" that you can find in your ASPECT build directory?

**Comment by XieJChris** [comment]
@naliboff @tjhei 
![1](https://user-images.githubusercontent.com/31496552/84582929-1a826e80-ae25-11ea-8496-8c24d250611c.jpg)
![2](https://user-images.githubusercontent.com/31496552/84582932-1d7d5f00-ae25-11ea-865d-7210fb94b3ca.jpg)
![3](https://user-images.githubusercontent.com/31496552/84582935-240bd680-ae25-11ea-8c71-b2dc2cf86a50.jpg)
![4](https://user-images.githubusercontent.com/31496552/84582979-d0e65380-ae25-11ea-93c5-6a0c99937b66.jpg)


the finite_strain.prm is the original file, I haven't make any changes, but it works fine when I run a file that doesn't contain any shared libraries.

**Comment by tjhei** [comment]
can you please post your detailed.log from your build directory?

**Comment by gassmoeller** [comment]
And does it work if you run the model while you are in the folder of the shared library? So probably your command would need to look like this (assuming you are inside `aspect/cookbooks/finite_strain`:
```
../../build/aspect finite_strain.prm
```
or alternatively (because ASPECT creates a symbolic link in a plugin directory when you compile it):
```
./aspect finite_strain.prm
```

The path to the shared library is given as a relative path inside `finite_strain.prm`, but it is a path relative to your active directory in the terminal, not relative to the position of the .prm file.

**Comment by tjhei** [comment]
I assume that we fixed your problem and that this is not an issue with ASPECT itself. Closing. If you still have an issue, please write in the forum and we will try to help.
