### ISSUE TITLE
modernize unity builds

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#3585]
The current way to do unity builds using COTIRE is only supported for cmake version 3.8 and older. This makes the feature a lot less useful and more difficult to test (the 9.2 tester has a newer cmake version, see #3583 ).
I would suggest:
a) remove cotire
b) investigate cmake unity builds [1], [2]

[1] https://cmake.org/cmake/help/v3.18/prop_tgt/UNITY_BUILD.html
[2] https://onqtam.com/programming/2019-12-20-pch-unity-cmake-3-16/

I looked into enabling ``CMAKE_UNITY_BUILD``, but this doesn't have any effect...

**Comment by gassmoeller** [comment]
I agree that we need to replace cotire (it has reached end of support anyway, https://github.com/sakra/cotire#cotire). Ideally replacing by native cmake precompile headers and unity build sounds best, but it has this some limitations (https://cmake.org/cmake/help/v3.16/prop_tgt/UNITY_BUILD.html):

```
Any source file that has a non-empty COMPILE_OPTIONS, COMPILE_DEFINITIONS, COMPILE_FLAGS, or INCLUDE_DIRECTORIES source property will not be combined into a unity source.
```
As far as I can tell we use these a lot for our files (maybe I misunderstand how we use them vs what this limitation is). It seems the fix would be to create a configuration file that defines the necessary macros and is created by cmake during configuration? Like we do for revision.h.in in include/aspect or in world_builder_config.cc.

At least precompiling headers is already possible and gives some real benefit:

Without precompile: make -j12

real    7m54.763s
user    85m49.481s
sys     4m25.993s

With precompile global.h: make -j12
CMakeLists.txt:470: `TARGET_PRECOMPILE_HEADERS(aspect PRIVATE <aspect/global.h>)`

real    5m26.267s
user    54m37.578s
sys     3m43.557s

With precompile simulator_access.h: make -j12
CMakeLists.txt:470: `TARGET_PRECOMPILE_HEADERS(aspect PRIVATE <aspect/simulator_access.h>)`

real	3m2.929s
user	24m40.395s
sys	2m21.270s

Unfortunately precompiling simulator_access.h breaks if `ASPECT_WITH_WORLD_BUILDER` is on:
`cc1plus: warning: /home/rene/software/aspect-debug/CMakeFiles/aspect.dir/cmake_pch.hxx.gch: not used because 'ASPECT_WITH_WORLD_BUILDER' is defined [-Winvalid-pch]`

I dont understand why `ASPECT_WITH_WORLD_BUILDER` is different than `ASPECT_HAVE_LINK_H` or `ASPECT_SOURCE_DIR` (they dont create problems if the world builder is off).

The best middle option might be the following:

With precompile global.h and all major includes in simulator_access.h: make -j12
CMakeLists.txt:470: `TARGET_PRECOMPILE_HEADERS(aspect PRIVATE <aspect/global.h> <aspect/introspection.h> <aspect/parameters.h> <deal.II/particles/particle_handler.h> <deal.II/base/table_handler.h> <deal.II/base/timer.h> <deal.II/base/conditional_ostream.h> <deal.II/distributed/tria.h> <deal.II/dofs/dof_handler.h> <deal.II/fe/fe.h> <deal.II/fe/mapping_q.h>)`

real	3m26.878s
user	30m53.368s
sys	2m58.199s

I will open a PR for that option.

Understanding better what prevents the unity build would still be helpful.

**Comment by tjhei** [comment]
> As far as I can tell we use these a lot for our files

Ah, interesting. I did not see that limitation. 

> Like we do for revision.h.in in include/aspect or in world_builder_config.cc.

Yes, I think that would make sense to do. Do you want me to take a look?

**Comment by gassmoeller** [comment]
>  Do you want me to take a look?
Yes that would be great.

**Comment by tjhei** [comment]
this is what I get with ``cmake -G Ninja -DCMAKE_UNITY_BUILD=ON -D CMAKE_UNITY_BUILD_BATCH_SIZE=10 ..`` (without precompiled headers):
```
$ cd build-nounity
$ time ninja -j 16
real    3m29.217s
$ cd build-unity
$ time ninja -j 16
real    0m44.356s
```
Wow.

**Comment by gassmoeller** [comment]
Wow indeed :smile:. With all the changes unity builds may be better even for standard installations. If the unity builds turn out to be stable across systems I am not opposed to discussing making them new default. For frequently recompiling a single source file precompiled headers may still be better though.

**Comment by tjhei** [comment]
> With all the changes unity builds may be better even for standard installations.

It requires more memory (I haven't checked the maximum, but it is at least 2-3GB). That could be problematic.

> For frequently recompiling a single source file precompiled headers may still be better though.

Even small changes seem quite fast. I am not sure if it makes sense to combine precompiled headers with unity builds.

**Comment by gassmoeller** [comment]
I did some testing with #3587 and unity builds, and on my system as soon as you have more unity build targets than available jobs, precompiling the headers is worth it. If you have exactly as many targets as available jobs then precompiling the headers costs you a few (<10) seconds. 

The biggest gain I saw from precompiling was for the default batch size of 8 source files per unity target and 12 jobs. Precompiling reduced the real time from 1:32 to 1:12. The best time I could get was with a batch size of 25, which exactly creates 12 build targets for my 12 jobs, and no precompiling, which took 1:05 (vs 1:09 with precompiling). So precompiling improves the compile time for nearly every unity build and brings it very close to the optimal time. I think it is worth it.

**Comment by gassmoeller** [comment]
About memory consumption (all with precompiled headers, but without world builder for now, measured with /usr/bin/time --verbose, field `Maximum resident set size (kbytes)`). Not sure if this is maximum consumption of one build job, or sum of all jobs:

single unity build target: ~6.6 GB
12 concurrently compiled targets: 3.3 GB
default batch size of 8 (38 targets, 12 concurrently): 2.5 GB
without unity build: ~2.5 GB

**Comment by tjhei** [comment]
I tested resident size by compiling with ``-j 1`` and I get:
unity (batch size 10): 3.3GB
no unity: 2.7GB
So this is not bad at all.

**Comment by tjhei** [comment]
I just realized that testing is a bit problematic: we require cmake 3.15, but ubuntu 18.04 that I am using in #3583 bundles cmake 3.10 only. Manually install a newer version?

**Comment by tjhei** [comment]
> Manually install a newer version?

this is now what I do in #3583

**Comment by tjhei** [comment]
anything left to do here, @gassmoeller ?

**Comment by gassmoeller** [comment]
I think we can close this. I was playing with the thought of setting unity build on by default if cmake supports it (because most users will not use it otherwise). What do you think?

**Comment by tjhei** [comment]
> What do you think?

I don't feel strongly about it but I also haven't experimented with it to know if it has other consequences for IDEs, warnings/errors while developing, potentially missing headers, etc..
If you want we can go and enable it and see if we run into issues.

**Comment by gassmoeller** [comment]
Lets give it a try. If we encounter too many problems during the hackathon or afterwards we can disable it again for the next release.

**Comment by tjhei** [comment]
I guess we are done with this now. Great work, thanks! :partying_face:

**Comment by tjhei** [comment]
With both enabled, I just received this on one of my branches (even with -j1):
```
In file included from CMakeFiles/aspect.dir/Unity/unity_26_cxx.cxx:10:0:
/ssd/aspect-git3/source/postprocess/velocity_boundary_statistics.cc:262:1: internal compiler error: Segmentation fault
 }
 ^
```
I don't quite understand what is happening, but it goes away if I disable precompiled headers. I will see if this appears again.
