### ISSUE TITLE
slow CI since switching to deal.II 9.2

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#3630]
It looks like our testing time increased substantially with the switch to the newer docker image. 
For example in #3425 
![image](https://user-images.githubusercontent.com/1531285/88964293-34fa9500-d277-11ea-9668-d2a40ab0087c.png)
We go from 16 to 70 minutes

This might be related to:
- [ ] MPI oversubscription and tests using too many cores, but this should have been a problem beforehand or not? 
- [x] See #3624 for reducing the number of ranks for 2 tests
- [x] Two sequential tests now take way too long (20 and 45minutes) and currently slow down the prebuild, see #3618 for a fix
- Note that we now do a unity and nonunity build, so the build is okay to be slower. See #3621

**Comment by gassmoeller** [comment]
I had another idea for why tests under 9.2 are so much slower. Between 9.0 and 9.1 deal.II disabled -Og for gcc and fell back to -O0 for debug mode (dealii/dealii#7207). I liked the change because I often debug under gcc and often had to set -O0 manually to debug, but this may cause the tester to be slower (there is even a discussion there that the same happened to the deal.II testers). Should we aim to create a tester with -Og, because we do not care about debugability?

**Comment by tjhei** [comment]
Wow. I totally forgot about that. This is worth looking into and explains the slower assembly. Thank you!

**Comment by tjhei** [comment]
update: we are now down to 35min (that still includes 6min for the no-unity build, that will be gone).

**Comment by bangerth** [comment]
We don't actually care about debugging symbols and similar on the CI machines. Why not use `-O3` and similar flags even for debug mode? All that's necessary is to run in debug mode, but that doesn't mean that we have to use flags that actually make debugging possible.

**Comment by gassmoeller** [comment]
Either are very good options. I was not aware that the asserts depend on the build type and not on the flags, although it makes sense of course. Learned something here :-). @tjhei do you have time to create a docker image with faster flags? If not I can give it a try.

**Comment by gassmoeller** [comment]
Oh, I only saw #3643 after my previous post. But #3643 will only compile ASPECT with different option. I would guess the expensive part is actually happening inside deal.II?

**Comment by tjhei** [comment]
> But #3643 will only compile ASPECT with different option.

I am not sure how much of a difference it makes to only optimize ASPECT, but I assume it makes some difference regarding inlining (everything that can be inlined from the deal.II headers will be inlined even if deal.II is compiled with -O0). So I wanted to try that first.

> Do you have time to create a docker image with faster flags?

I was planning on doing that as well. One step at a time. :-)

**Comment by egpuckett** [comment]
@tjhei Why does a link to this issue show up in our PR #3425 for the VOF Benchmark Cookbook?  Do we need to edit something in the Cookbook / PR?

**Comment by tjhei** [comment]
> Why does a link to this issue show up in our PR #3425 for the VOF Benchmark Cookbook? Do we need to edit something in the Cookbook / PR?

Nothing to do for you. Sorry for the confusion. I just used this PR to rerun the tester a couple of times.

**Comment by gassmoeller** [comment]
But since we are active again on this issue: @tjhei could you still look into compiling a version of the `tjhei/dealii:v9.2.0-full-v9.2.0-r1-gcc5` docker container with -O1 or -O3 but in debug mode? Currently I have most of the CIG testers disabled, because they would timeout. Alternatively I can also compile an image myself, or increase the time limits in the Jenkinsfile.

**Comment by tjhei** [comment]
Yes, I am working on it. Sadly, we do not compile cleanly with O1: https://github.com/dealii/dealii/pull/10786

The other question you and I need to discuss is the mpich vs openmpi question. Should we ignore that for now?

**Comment by gassmoeller** [comment]
Fixed by #3848.
