### ISSUE TITLE
class instantiations with implementations in different .ccs?

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#3651]
We have various issues with unity builds because we have implementations and instantiations split into separate files (#3637, #3650, ...). I don't like that solution and we have this also in core.cc, assembly.cc, helper_functions.cc, etc..
Questions:
1. Is this even correct what we do without unity builds? We list function instantiations at the bottom for file that do not instantiate the main class. For example https://github.com/geodynamics/aspect/blob/master/source/simulator/assembly.cc#L1254
But we are not consistent about it.
2. What do we do to avoid this?
a. Exclude from unity build or explicitly reorder as in https://github.com/geodynamics/aspect/blob/d84f68a39a22c37a0cd9789126840f9c76bfe05a/CMakeLists.txt#L31-L35 ?
b. Move everything into one .cc
c. Turn the helper implementations into a ``xyz.template.h`` and include in the main file.

**Comment by bangerth** [comment]
It's legal to do what we do if you split things up into different .cc files, but it's going to lead to different results (specifically: errors) if you combine things.

If it's a relatively small number of affected files, then I'd just remove them from the unity builds -- these are presumably all large files that were created specifically because we didn't want to put everything into one file. The vast majority of ASPECT remain plugins that are all in one file and that can be combined into unity build files. Every other solution is certainly more complicated and, more importantly, fragile.

**Comment by tjhei** [comment]
> If it's a relatively small number of affected files, then I'd just remove them from the unity builds

I go a similar route in #3653. Just moving the files instantiating the class to the end of the list makes sure that these errors can not appear.
