### ISSUE TITLE
Possible causes of triggering 'Assemblers Stokes Incompressible Terms' error?

### ISSUE THREAD

**Issue by XieJChris** [geodynamics/aspect#3873]
Hey guys, I encountered an error like this:
<img width="1526" alt="Screen Shot 2020-10-24 at 10 15 12 AM" src="https://user-images.githubusercontent.com/31496552/97065801-c2355780-15e2-11eb-8969-8601384d42c0.png">
It seems to be related to 'Assemblers' ? Can anyone offer me some suggestions to solve this problem? Appreciate.

**Comment by MFraters** [comment]
Hey @XieJChris,
Thanks for reporting this problem! From what you are showing I can't directly see what the problem is, besides that it is a floating point error, which are in my experience usually caused by a division by zero somewhere in the code. You are correct that it seems to happen in the assemblers, but to investigate the problem it would be helpful to have a bit more information.

There are a few specific questions I have. 

1. If you could share a prm which is as simple as possible and could replicate the problem that would help us find the issue. 
2. I see that a shared library is being loaded, what is it and could the problem be in there? 
3. are you running this in optimized or debug mode? If you are running this in optimized mode, try recompiling it in debug mode, because that might already trigger an assert indicating what the problem is.

**Comment by XieJChris** [comment]
@MFraters Thanks for replying, I think I've found the cause, I ported the code to another code that had ran successfully before, and it worked, well, it does seem to be a floating point exception but caused by numeric bounds that used to limit the range of the results (e.g., std::max(max_visc, computed_viscosity)), which is pretty weird.
