### ISSUE TITLE
Iterate error code -2: numerical breakdown

### ISSUE THREAD

**Issue by XieJChris** [geodynamics/aspect#3875]
Hi all,

It looks like that I've got a strange error, as you can see, the ASPECT seems to have successfully loaded the code and stared running, but soon the error occurs, the additional information is: 
<img width="1526" alt="Screen Shot 2020-10-28 at 8 41 39 AM" src="https://user-images.githubusercontent.com/31496552/97376859-7394ff80-18f9-11eb-9428-adf7a5edcce9.png">

The iterative (bottom right) solver in BlockSchurPreconditioner:vmult did not converge to a tolerance 5.4002545113719711e-09. It reported the following error:

An error occurred in line <497> of file </home/chris/ASPECT/tmp/unpack/deal.II-v9.2.0/source/lac/trilinos_solver.cc> in function
    void dealii::TrilinosWrappers::SolverBase::do_solve(const Preconditioner&) [with Preconditioner = dealii::TrilinosWrappers::PreconditionBase]
The violated condition was: 
    false
Additional information: 
    AztecOO::Iterate error code -2: numerical breakdown.

Is the error normal? And how to fix it? Thanks.

**Comment by tjhei** [comment]
> Is the error normal? And how to fix it?

The information for you to take from this error is that the linear Stokes solver did not converge. This can happen if your problem is difficult to solve (large viscosity contrasts), under-resolved (mesh is too coarse), or ill-defined (inconsistent boundary conditions like forced inflow for an incompressible problem).

Without knowing more about the problem you are trying to solve, it is hard to help you.

**Comment by XieJChris** [comment]
@tjhei Thanks for replying. Listing possible causes is helpful for me. The problem has been solved, and it was indeed caused by an ill-defined boundary condition :)
