### ISSUE TITLE
Including units within pvtu metadata output 

### ISSUE THREAD

**Issue by ahollyday** [geodynamics/aspect#4128]
I'm trying to specify field units in the outputted pvtu (and other outputted file formats) metadata.  This will make reading in ASPECT output easier with the Yt-project and will prevent confusion related to future changes in units.  Any help/ direction would be awesome!

**Comment by bangerth** [comment]
The first step would be to find out how this would be represented in the .pvtu file format. If you look at one of the .pvtu files produced by ASPECT, you'll see that it's clear text XML. You might have to look up online what kind of information can appear in this file, or check the kind of files other programs produce that contain this information.

If you know how this is supposed to look like, I can tell you where to make the relevant changes!

**Comment by bangerth** [comment]
@chrishavlin Let's take @ahollyday 's discussion about metadata in VTK here -- that brings everyone who knows where that needs to be implemented into one place.

From our perspective, we can do whatever is easiest for you. Encoding stuff in variable names is easy but seems silly. Let's write this into metadata in the same way as we already do with time step ("cycle") and time variables. For example, this is how this looks in deal.II output right now:
```
<VTKFile type="UnstructuredGrid" version="0.1" compressor="vtkZLibDataCompressor" byte_order="LittleEndian">
<UnstructuredGrid>
  <FieldData>
    <DataArray type="Float32" Name="CYCLE" NumberOfTuples="1" format="ascii">42</DataArray>
  </FieldData>
...
```
I'm not entirely sure what else VTU allows in the `FieldData` tag, but it seems like it's basically any kind of meta-data and both Visit and Paraview seem to understand what we're trying to say here. The manual at https://vtk.org/wp-content/uploads/2015/04/file-formats.pdf doesn't say what FieldData actually is.

So, if it would be useful to express units somehow in this section, then that's what we should do. I suspect it should be some kind of map from the name of the fields for which we store data (a string) to the physical units (also a string)? Since we have nothing at the moment, there are also no compatibility concerns: *You* can tell us how you'd like units to be expressed, and that's exactly what we'll do :-)

**Comment by chrishavlin** [comment]
Great! Thanks for the ping! 

From my perspective it doesn't matter too much where the metadata sits. I'm using a generic xml parser to read in the pvtu files so I can easily pull the info from anywhere. I'm with you on on the "I'm not entirely sure what else VTU allows in the FieldData tag" but the most natural place IMO would be within each `DataArray` delcaration, e.g.:

```
<UnstructuredGrid>
  <FieldData>
    <DataArray type="Float32" Name="CYCLE" NumberOfTuples="1" format="ascii" Units="">42</DataArray>
    <DataArray type="Float32" Name="T" NumberOfTuples="1" format="ascii" Units="K">42</DataArray>
  </FieldData>
```

So as long as that (1) is possible and (2) does not cause problems with Paraview and Visit, that's where I'd put the info. But if it's easier for some reason to leave those tags alone and add a separate mapping that would work just fine as well. I'm not familiar enough with VTK's xml format -- does it allow for custom attributes? 

On the subject of how to set the units: the units should be stored as a string. they'll get eventually get used by the `unyt` package [https://unyt.readthedocs.io/en/stable/](https://unyt.readthedocs.io/en/stable/) 

Some notes on formatting the strings: 

* any MKS units will work, some non-MKS units will work. I believe that all the fields in ASPECT should have well defined units in `unyt`
* units don't have to be the base unit. e.g., `'m'`, `'km'`, `'cm'` are all valid, `unyt` is smart enough to figure it out. 
* unitless fields should have units set to an empty string, `""` , but on my end I can also add some logic to read in fields as unitless if the `Units` metadata tag is not there so that old pvtu files can still be loaded. 
* the strings should follow pythonic operations. meaning, `"m/s"` and `"m * s**-1"` are both correct velocity units, but `"m * s^-1"` will error. 
* unit names should be singular, meaning: use "Myr" not "Myrs".

If you want to experiment with `unyt` and check that a unit string is valid, you can install `unyt` with `pip install unyt` or `conda install -c conda-forge unyt` and then from a python terminal:

```python
from unyt import unyt_quantity
unyt_quantity(1, 'Myr')
```
That will throw an error if the string is not recognized by `unyt`. If there are units in ASPECT that are not recognized by `unyt` there are ways to deal with that! But as I don't think that will be the case, I won't get into details here. 

And just to connect all the dots, here's a link to the yt PR that this discussion relates to: [https://github.com/yt-project/yt/pull/3109](https://github.com/yt-project/yt/pull/3109). I'm planning to rebase and tidy up that PR in the coming weeks now that yt4.0 was just released, so this great timing to get in some metadata for the units on the ASPECT side!

**Comment by chrishavlin** [comment]
A very brief update, paraview at least does not seem to mind if there are metadata tags that it doesn't recognize. I didn't get any errors or warnings upon loading when manually adding a `Unit` attribute to an already generated pvtu, so it thankfully seems that Paraview will simply ignore attributes that it's not looking for. Not sure if there's further tests that should be done? For reference, the edited pvtu looked like:

```
<?xml version="1.0"?>
<!--
#This file was generated by the deal.II library on 2021/3/8 at 21:38:20
-->
<VTKFile type="PUnstructuredGrid" version="0.1" byte_order="LittleEndian">
  <PUnstructuredGrid GhostLevel="0">
    <PPointData Scalars="scalars">
    <PDataArray type="Float32" Name="velocity" NumberOfComponents="3" format="ascii" Unit="m/s"/>
    <PDataArray type="Float32" Name="p" format="ascii" Unit="Pa"/>
    <PDataArray type="Float32" Name="T" format="ascii" Unit="K"/>
   #### CUT OUT SOME LINES HERE ####
</VTKFile>
```

IMO that's a little cleaner than adding a separate field-unit mapping tag as you don't have to repeat the field `Name`, but it makes no difference from the perspective of parsing it for yt -- this only needs to happen once when initially instantiating a yt dataset object, so the amount of extra work to use a field-units mapping dict will be negligible.

**Comment by bangerth** [comment]
Ha, you had the same idea as me, and I tried the same thing using Visit and it works there as well :-) In fact, I looked at the individual VTU file and did this:
```
    <DataArray type="Float32" Name="T" format="binary" units="K">
           AQAAAABEAQAARAEA7nAA...
```
We could attach the data to both places.
So yes, let's go with that then and attach units right with the field declaration!

**Comment by bangerth** [comment]
@ahollyday -- let's talk about this tomorrow morning if that's ok with you!

**Comment by ahollyday** [comment]
@bangerth sounds great!

**Comment by chrishavlin** [comment]
hey @ahollyday I wrote up a (p)vtu tester that will parse a pvtu or vtu file, identify the data elements, pull out the field and units string for each and check that it works with `unyt`. To use it:

1. Download or copy `vtu_unit_test.py` from here https://gist.github.com/chrishavlin/744d7b24a91b73a495a44bf0306806bf 
2. Install `xmltodict` and `unyt` (`pip install xmltodict`, `pip install unyt`). You'll also need a somewhat recent python version (I think it should work as far down as python 3.5).
3. From a terminal, you can run
    
```
$ python vtu_unit_test.py /path/to/file.vtu /path/to/different/file.pvtu
```

and it will print out some test results like:

```
testing file aspect/output_shell_simple_2d/solution/solution-00000.pvtu

    Could not find a units tag for velocity
    Could not find a units tag for p
    Could not find a units tag for T

testing file aspect/output_shell_simple_2d/solution/solution-00001.pvtu

    velocity passed unit test with m/s
    p passed unit test with nondimensional units
    *** test failure! *** the unit string bad for T could not be handled. Try `import unyt; unyt.unyt_quantity(1, bad)`  from a python shell to see the full error message.
```
The docstring in `vtu_unit_test.py` has some more examples and info -- I assumed you were going to use `Units` as the new attribute name, but if that's not the case the docstring has some notes on using a different name.

**Comment by bangerth** [comment]
The deal.II part is now here: https://github.com/dealii/dealii/pull/12556.

@chrishavlin If you want to take a look at how this is now encoded: Here is a VTU file https://github.com/dealii/dealii/pull/12556/files#diff-33e8b5d06d26955dda1ca2805b029a2a7f48ef3d8315493bf343e67906c1e178 and a corresponding PVTU file https://github.com/dealii/dealii/pull/12556/files#diff-e5412f57e6b36d9c315d1951d82cecbab640267e05ab8c4187a1bab4aa4be00d In these files, the content of the `<DataArray>...</DataArray>` has been stripped out to save some disk space.

**Comment by chrishavlin** [comment]
That will work perfectly!

**Comment by tjhei** [comment]
What is the status of this, @bangerth ?

**Comment by bangerth** [comment]
We put the units into the .vtu file, but it seems like we're not putting them into the .pvtu file. I'm investigating.
