### ISSUE TITLE
How to visualize all compositional field/ material field.

### ISSUE THREAD

**Issue by tyszwh** [geodynamics/aspect#4297]
Hi, everyone.
I'm a new guy for using aspect code.
I have a question about the compositional field/ material field. 
For now, every compositional field is separate property in output files. Is there a visualization choice for ParaView to show all compositional field/ material fields? For example, seven compositional fields are labeled 1, 2, 3, 4, 5, 6, 7 in one property and could be colored with different colors. (This can be done through a simpler calculation in ParaView. But a direct output should be better)

**Comment by bangerth** [comment]
@tyszwh Do I understand right that you want something like this:
* If compositional field 1 has a value > 0.5, then use color 1
* If compositional field 2 has a value > 0.5, then use color 2
* ...
? What do you do if more than one compositional field has a value > 0.5?

**Comment by tyszwh** [comment]
Sorry for my confused expression.
I mean the different materials, such as upper crust, lower crust, mantle, etc., are displayed in one vis window simultaneously and could be colored with different colors. This is similar to the initial model in most articles.

**Comment by bangerth** [comment]
Right, so I think what you are asking for is what I described above. The question is: Given that there are N compositional fields, how do you want to identify from the N values of the fields at a given point whether it is mantle material, crust material, etc? ASPECT doesn't track that a point is part of the mantle; it only tracks what the values of the N compositional fields are, and you have to somehow determine what these N values *mean*.

**Comment by tjhei** [comment]
In other words, what you are trying to have is currently not possible.
We might be able to do something like this in the future after we categorize compositional fields as described in #4246

**Comment by tyszwh** [comment]
Ok, Thanks for your reply.

At least, in the initial time step, we can display the material fields in Paraview like below. 

![Screenshot from 2021-08-03 08-51-42](https://user-images.githubusercontent.com/8081772/127940934-0691fdb8-3044-4d72-8536-beb9c1ebbcbc.png)

But I guess the identification of different materials may not be very accurate with the running of the model.
![Screenshot from 2021-08-03 08-58-28](https://user-images.githubusercontent.com/8081772/127941336-9170495f-d5dc-497c-9aaf-9a1de059b1b9.png)

**Comment by bobmyhill** [comment]
Hi @tyszwh 

Those images are what I would expect. In simulations where different compositions are modelled using fields, each composition fraction is continuous between 0 and 1. All the evaluation points might have compositional values in {0,1} at the first time step, but that will not be true as the material advects due to numerical diffusion.

So there are two things to think about:
- Is the diffusion a problem in your study? (Should you adaptively refine your mesh using composition as a discriminant to minimize the diffusion? Would particles be a better choice?) This relates to @tjhei's comment; in future we could artificially restrict values of compositional fields to 0 or 1, which would preclude numerical diffusion of composition. However, that solution would not respect conservation of mass. We would need to think carefully about whether that was a sensible thing to do.
- How do you want to plot composition in Paraview, given that the values of the fields will not generally be in {0,1} (@bangerth's comments)? You have a vector of compositions __x__ = [x1, x2, x3, x4...] and you want to represent these with a single scalar. Your solution (above) is to take the dot product of __x__ and a vector of increasing positive integers, i.e. __x__.dot([1, 2, 3, 4, ...]). You could alternatively plot the index of the field with the maximum value, which would make a plot with sharp boundaries, but they might look a little jagged in areas where the mesh is coarse.

**Comment by tyszwh** [comment]
Hi @bobmyhill 
The model above is just a simple test with single advection. As you said, I  calculate the material filed simply through (C1*1+C2*2+C3*3+.....). It may be worked at the first time step. But all the evaluation points will not be true as the material advects due to numerical diffusion and thus the values of the compositional filed varied as @bangerth's comment.
As a new user of Aspect, there are many things I need to understand.

**Comment by bobmyhill** [comment]
Hi @tyszwh we're always happy to help! Let us know if you have any more questions.

You are, of course, very welcome to raise issues or suggest improvements with us here on GitHub. However, if you want to ask questions about using ASPECT, I can also recommend the forum (https://community.geodynamics.org/c/aspect).

**Comment by tyszwh** [comment]
@bobmyhill 
Very cool forum, thanks for it.

**Comment by MFraters** [comment]
The issue seems resolved. Feel free to reopen if it is not.
