### ISSUE TITLE
Some question about initial topography and material model

### ISSUE THREAD

**Issue by tyszwh** [geodynamics/aspect#4328]
Hi, everyone

After several days of testing, I have some remaining questions. 

1 The initial lithostatic pressure boundary and Initial adaptive refinement do not work when adding the initial topography in the model.
2  how do melting (like melting simple model) work together with the viscoplastic material model, should I write a new plugin to combine them?
3 An option to select a specific flow law for each assigned composition(Is it related to this? https://github.com/geodynamics/aspect/pull/4239).

**Comment by anne-glerum** [comment]
Hi @tyszwh 
These kind of overarching questions might be better to ask on the CIG ASPECT forum (https://community.geodynamics.org/c/aspect/). Here some quick comments from my side.
1. The initial lithostatic pressure boundary condition is not allowed in combination with mesh deformation/initial topography because when the surface deforms, the reference pressure profile that is computed at the start of the model run might not be representative any more. However, initial topography should work with Initial adaptive refinement. Note that the most recent way to prescribe initial topography is through initial mesh deformation. 
2. There is no model where melt interacts with the viscoplastic rheology yet. Several people are working on it though. If you want to combine different elements of material models, you could start with the `compositing` material model.
3. At the moment, it is not possible to directly specify a flow law per composition. However, if you choose a composite rheology, and for example only wish diffusion to act for one composition, you could provide a very small prefactor (e.g. 1e-50) for the dislocation creep for that composition so that it will not play a role.
Hope that helps!

**Comment by tyszwh** [comment]
Hi, @anne-glerum 
Thanks for your reply.
 Your explanation is very clear. I get the picture now.
