### ISSUE TITLE
Adding a free surface on a restart causes segmentation fault

### ISSUE THREAD

**Issue by erinheilman** [geodynamics/aspect#4341]
When adding a free surface to a 2D spherical shell model that has already computed timesteps, and then restarting I get a segmentation fault. I ran on debug to see why it was failing and got this error message. 
<img width="1773" alt="Screen Shot 2021-09-03 at 12 11 08 PM" src="https://user-images.githubusercontent.com/69014916/132043528-305127ef-1a5f-4386-865c-b7d20d26a342.png">
I've included the prm file that is updated with the free surface parameters. Is this an issue with my parameter file or something that shouldn't be done?
[2D_full_depth_dep_ys_nosw_nosh_free_surface.txt](https://github.com/geodynamics/aspect/files/7107583/2D_full_depth_dep_ys_nosw_nosh_free_surface.txt)

**Comment by gassmoeller** [comment]
This is something we do not generally support. Changing model parameters between restarts is not guaranteed to work (although it does work for many parameters). However, for free surface models to be restarted the model requires the amount of accumulated deformation for each mesh vertex which of course was not saved during the restart before. With some effort there could be hack to support this (detecting if no deformation was stored and then initializing it with 0 deformation), but that will still come with some caveats such as that we use a different finite element mapping for models with mesh deformation, which will change the solution slightly and potentially cause problems for the solver to converge. 

Here is what you could try instead:

Start the model with mesh deformation already enabled, but set the boundary deformation model to `function` instead of `free surface` and the velocity boundary condition to tangential instead of empty. The default values for function are to not prescribe any deformation, so you will have the whole mesh deformation machinery activated, but the boundary should not actually deform and there should be no flow through the boundary. Then during the restart replace the function model by the free surface model and remove the boundary condition for velocity. This may still provide some convergence problems for the solver in the step after the restart, but it may just work (make sure to think of a test case, this solution is experimental).

**Comment by erinheilman** [comment]
Thanks Rene, I'll try it on a simple model and see if it works.

**Comment by elodie-kendall** [comment]
Hi Erin, Rene, I did already try this a few months ago- https://github.com/geodynamics/aspect/issues/4029. However, it didn't work because: "The pressure normalization method that was stored in the checkpoint file is not the same as the one you currently set in your input file. These need to be the same during restarting from a checkpoint."

**Comment by erinheilman** [comment]
Yes, I got that message too. I got it to work by setting pressure normalization to no from the beginning of the model, then when switching to free surface it is satisfied

**Comment by elodie-kendall** [comment]
Ok thanks!

**Comment by bangerth** [comment]
Can this be closed?

**Comment by gassmoeller** [comment]
I think this can be closed.
