### ISSUE TITLE
compile aspect on M1 ARM

### ISSUE THREAD

**Issue by liumq12** [geodynamics/aspect#4535]
Hello, I already installed deal.II-v9.3.3 successfully using candi on M1 Mac. However, when I compile the aspect according to the instruction, I met a question. The detail is shown below. Can anyone help solve it? Thank you very much. 
$ make 
Consolidate compiler generated dependencies of target aspect
[  1%] Building CXX object CMakeFiles/aspect.dir/Unity/unity_40_cxx.cxx.o
g++-11: error: unrecognized command-line option '-Xarch_arm64'
make[2]: *** [CMakeFiles/aspect.dir/Unity/unity_40_cxx.cxx.o] Error 1
make[1]: *** [CMakeFiles/aspect.dir/all] Error 2
make: *** [all] Error 2

**Comment by tjhei** [comment]
It looks like your compilers might be mixed up. Please create a post at https://community.geodynamics.org/ with the following information:
1. detailed.log from deal.II (found in the installation directory)
2. detailed.log from the ASPECT build directory
3. output from ``mpicxx -v`` and ``env | grep MPI``
4. Any other information you can provide (how did you install deal.II, any environment variables set?)

I will close the issue here, because it doesn't seem to be an issue that needs fixing in ASPECT but rather a configuration problem on your end.

**Comment by liumq12** [comment]
Thanks for your reply. I try to post it at the website. However, I cannot open the website. I answer questions here. Could you give me some advice?

1-2. detailed.log files from deal.II and aspect are attached.
3. Output information are attached.
4. I install deal.II following the instructions at https://github.com/dealii/dealii/wiki/Apple-ARM-M1-OSX Environment variables setup through the below command:
#Export compiler environment
$ export CC=mpicc; export CXX=mpicxx; export FC=mpifort; export FF=mpifort; \
OMPI_CC=gcc-11; export OMPI_CXX=g++-11; export OMPI_FC=gfortran-11

On 4 Apr 2022, at 00:23, Timo Heister ***@***.******@***.***>> wrote:


It looks like your compilers might be mixed up. Please create a post at https://community.geodynamics.org/ with the following information:

• detailed.log from deal.II (found in the installation directory)
• detailed.log from the ASPECT build directory
• output from mpicxx -v and env | grep MPI
• Any other information you can provide (how did you install deal.II, any environment variables set?)
I will close the issue here, because it doesn't seem to be an issue that needs fixing in ASPECT but rather a configuration problem on your end.
