### ISSUE TITLE
Issue on page /user/install/virtual-machine/running-models.html

### ISSUE THREAD

**Issue by mibillen** [geodynamics/aspect#5084]
The run command is incorrect it should be:

~/aspect/build/aspect-release

The commang given in the manual does not work

**Comment by gassmoeller** [comment]
Thanks for the report, you are right that this command doesnt work. However it really should work, there is a link in `~/aspect/aspect` that points to the actual executable file. The problem is not that the command in the documentation is wrong, but that this link in the VM is broken at the moment (it points to the wrong location for the actual executable). We should fix the VM, as well as put a note in the documentation that the current version of the VM requires a different command.

@tjhei: The `aspect` link in `~/aspect` points to `/home/ubuntu/home/aspect/build/aspect`, but it should point to `/home/ubuntu/aspect/build/aspect`. Can you fix that in the build script for the VM? I  do not think this requires a rebuild of the VM at the moment, we can also just put a note in the documentation for now.

**Comment by tjhei** [comment]
Sure, will do. Are we sure we want to point to the release build?
