### ISSUE TITLE
Rip out latex stuff from doc/CMakeLists.txt

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#5304]
@gassmoeller Do you still have anything pending for this? I believe that nearly everything that's in `doc/CMakeLists.txt` is not necessary any more.

**Comment by gassmoeller** [comment]
I am done removing the latex content, I just skipped `doc/CMakeLists` because I was not sure what your plans for it where. We can remove everything that is no longer relevant. Eventually it will be nice to run sphinx and build the html documentation using cmake, but it will require some work (cmake needs to be able to find sphinx).

**Comment by bangerth** [comment]
OK, I'll see what I can rip out then!
