### ISSUE TITLE
CPO code needs more tests

### ISSUE THREAD

**Issue by gassmoeller** [geodynamics/aspect#5361]
As #5332 shows the CPO code is currently insufficiently tested. This is because tests were only possible when all the major components were in place. However, they are merged now, so we should add the necessary tests. @MFraters can you take a look?

Related to #3885.

**Comment by MFraters** [comment]
Yes, test are in the planning, and @srivatsvyas has already done some of the testing because the drexpp branch is based on this version instead of the paper version. 

I would like #5116 to be finished first so that the results can be completely compared in the integration tests. (There are already a lot of unit tests)

**Comment by MFraters** [comment]
I think the cpo is plugins are covered sufficiently now by the test. I think we can add more tests, but I think this issue can be closed.
