### ISSUE TITLE
renaming ASPECT

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#5391]
We had the conversation to rename ASPECT (while keeping the acronym) to reflect the fact that we now handle many other processes (core, surface, tectonics, etc.) and planetary bodies beside Earth.

I am posting some suggestions down here that I found on slack andelement. Feel free to upvote what you like.

**Comment by tjhei** [comment]
Advanced Solver for Planetary Evolution, Convection and Tectonics

**Comment by tjhei** [comment]
Advanced Solver for Planetary body Evolution, Convection, and Tectonics

**Comment by tjhei** [comment]
Advanced Solver for Planetary and Earth's Convection and Tectonics?

**Comment by tjhei** [comment]
Advanced Solver for Planetary, Earth's, and Celestial Tectonics

**Comment by tjhei** [comment]
Advanced Solver for PlanEtary Convection and Tectonics

**Comment by gassmoeller** [comment]
Hmm, so I know it seems like the vote went overwhelmingly towards "Advanced Solver for Planetary Evolution, Convection and Tectonics", which was also my favorite last week, and I am fine if we move forward with it (as #5392 suggests). 

However, after sleeping over it and considering it a bit more I may actually tend towards @tjhei's favorite ("Advanced Solver for PlanEtary Convection and Tectonics"). I dont propose to change our vote just based on my feeling, but can someone tell me if my following concerns are overblown or correct:
- If I practice in my head the line I would say during a talk: "I am using ASPECT - the Advanced Solver for Planetary Evolution, Convection and Tectonics" it is much more cumbersome than the shorter "I am using ASPECT - the Advanced Solver for PlanEtary Convection and Tectonics", probably because a list of 3 things is more difficult to remember than a pair of two. I know this is subjective, but shorter names tend to be better than longer ones.
- The "Evolution" in the current favorite would be in the wrong place. ASPECT is not primarily there for "Evolution" it is primarily a convection code, with applications in tectonics and other processes. Also "Evolution" as a term is so broad that it technically encompasses convection and tectonics. So in other words, if we would not need to build ASPECT as acronym, we would call it the "Advanced Solver for Planetary Convection, Tectonics, and Evolution".

Am I imagining things? Like I said if we stick with the current favorite I am fine with it, but I just wanted to hear other thoughts on the topic.

**Comment by bobmyhill** [comment]
Hi @gassmoeller,

I still prefer the longer choice, because it feels like a less obvious bacronym. For your points:
- I tend to say "the geodynamics code, ASPECT" in conversation, so I wouldn't have your problem. But you do give ASPECT talks infinitely more frequently than me ;)
- I agree to an extent, although evolution could more narrowly imply gross change in structure, with convection and tectonics being potentially pseudo steady state. Certainly that's how I define "planetary evolution" in talks that I give - convection and tectonics are a key part of that, but there's also melt and fluid migration that isn't captured by either of them.

**Comment by ljhwang** [comment]
Simpler is better. It took me years to say the long form of CIG without tripping over my tongue.

**Comment by tjhei** [comment]
@gassmoeller I thumbed up 2 suggestions by the way.

**Comment by bobmyhill** [comment]
@gassmoeller, yes I don't think there's any harm in waiting a few days! For what it's worth, I still like the PlanEtary one as a name - its just that the cons subjectively outweigh the pros for me.

**Comment by tjhei** [comment]
> I still like the PlanEtary one as a name

I guess one argument to use that one is because it is in the spirit of the old somewhat awkward acronym (containing ConvecTion). :-)

**Comment by gassmoeller** [comment]
> I guess one argument to use that one is because it is in the spirit of the old somewhat awkward acronym (containing ConvecTion). :-)

I made the same point to @jdannberg, but I think she prefers to get rid of the awkwardness, even if its part of our brand now :-)

**Comment by ljhwang** [comment]
I preferred to think of this as "distinctiveness". Resistance is futile.

**Comment by bobmyhill** [comment]
> I preferred to think of this as "distinctiveness". Resistance is futile.

ASPECT: Assimilation and Symbiotic Processor for Enhanced Collective Technologies?

**Comment by MFraters** [comment]
Like @bobmyhill, I usually just refer to the acronym ASPECT, and if needed I would describe it in my own words during a presentation. I don't think I often had to say the full name out loud. I do think the name change in general is important though, but more so because it highlights what we think the code represents. As long as all the elements we believe are important are in there, I don't really have a strong opinion on the full write out of ASPECT.

 I can see the advantages and disadvantages of `Advanced Solver for Planetary Evolution, Convection and Tectonics` and `Advanced Solver for PlanEtary Convection and Tectonics`. I have a slight preference for the Planetary Evolution one, since it is more clean, but PlanEtary is a nice reference back to ConvecTion, which I can appreciate. 

P.S. The more I think about it the more appropriate `Assimilation and Symbiotic Processor for Enhanced Collective Technologies` is, since we have been and are working integrating all kinds of codes into ASPECT ;)

**Comment by gassmoeller** [comment]
#5392 has been merged so this discussion is closed ;-). However, let's keep this issue open for a while until we have made the change in all related places (website, CIG site, etc.).

**Comment by bangerth** [comment]
Does anyone know of a place that is left to convert?

**Comment by gassmoeller** [comment]
I think all places have been converted. Let's close this issue and deal with any remaining places when we find them.
