### ISSUE TITLE
cleanup, test, and fix averaging

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#581]
We currently have duplicated functionality for averaging quantities in MaterialModel::Interface and the averaging material model. We should unify the averaging code and fix a couple of issues while we are at it. Also see #578

**Comment by bangerth** [comment]
I suggested the code duplication because (i) I thought that averaging is a common enough operation in the community that it is worthwhile to make the most common operations available quickly, (ii) that the averaging material model is a nice example of something I can see happen more frequently, namely one material model modifying the behavior of another.

I agree that code duplication is in general a bad idea, but I think it can be justified here.

**Comment by bangerth** [comment]
What to do about this one? I'm ok with the current state, for the record.

**Comment by gassmoeller** [comment]
Since this issue is stale I suppose we are fine with the current state of duplication (I do not mind)? I will therefore close this issue. Feel free to reopen more specific issues about individual points to improve.
