### ISSUE TITLE
aspect with deal.II 64bit dof indices not compiling

### ISSUE THREAD

**Issue by gassmoeller** [geodynamics/aspect#611]
Did anyone ever compile aspect with the DEAL_II_WITH_64BIT_INDICES option enabled? I get an error, because we sometimes use `unsigned int` as an dof index. I will prepare some patches tomorrow, this is just to see if it is just my compiler that complains.

**Comment by gassmoeller** [comment]
btw. this is happening with an ASPECT version from July and the most recent deal.II

**Comment by tjhei** [comment]
I haven't done that in a while (if ever). Patches are always welcome of course.

**Comment by bangerth** [comment]
I used to do it every few revisions of deal.II and post it on the regression test site at http://cdash.kyomu.43-1.org/index.php?project=aspect&display=project but I see that they don't seem to get there any more. Might have to check what is happening. In any case, patches are of course welcome, as Timo says -- and should in fact be pretty easy to write since the error messages are pretty obvious if you know what causes them.

**Comment by gassmoeller** [comment]
Fixed by #613
