### ISSUE TITLE
Document running the testsuite

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#726]
How to run the testsuite, and how to add tests, is apparently not currently documented. Fix this.

**Comment by dsarahstamps** [comment]
A few comments:

go to aspect/build directory
run: 
ctest
or 
ctest -j4 (to run on 4 processors)

If you have compiled aspect with ASPECT_RUN_ALL_TESTS=ON then you will run the full suite of test. Otherwise initiate tests by running:
make setup_tests

You will see: 
Scanning dependencies of target setup_tests
[100%] Enabling all tests ...
Added 270 tests.
[100%] Built target setup_tests

A tests/ directory is created in your top level aspect directory with 270 tests. 
To run a specific test, i.e. for tests that have the term "periodic":
ctest -R "periodic" -j4

**Comment by bangerth** [comment]
See also #438

**Comment by gassmoeller** [comment]
Resolved by #1168.
