### ISSUE TITLE
Move WGS 84 functions into utilities

### ISSUE THREAD

**Issue by bangerth** [geodynamics/aspect#798]
These are currently in the EllipsoidalChunk class, but we will surely make more use of the WGS84 model at one point or other, and it would be useful to move this into the general `Utilities` namespace.

**Comment by bangerth** [comment]
@trajaona -- per your request.

**Comment by MFraters** [comment]
I agree that the function in the EllipsoidalChunk class should be moved to Utilities, because I for example also need it in the computation of the boundary velocities and initial conditions. Please make sure that it stays the generalized ellipsoidal version, and doesn't change back into the specific WGS84 model :)

I will have to look better at it later, but if we also have the move the functions that are blocking the 2d implementation than it might be better to fix that problem first. The hackaton might be a good moment to look at this.

**Comment by MFraters** [comment]
I will take a look at this.

**Comment by MFraters** [comment]
I have some idea's about what I could do with this, but I guess it is better to talk about it in relation to what we want to do with the ellipsoidal chunk geometry and the topography.

**Comment by gassmoeller** [comment]
This was already closed by #1054 and #1065.
