### ISSUE TITLE
Compositional field  might not be global mass conserved in time when AMR is used

### ISSUE THREAD

**Issue by yinghe616** [geodynamics/aspect#906]
When I was testing the Van Keken smooth benchmark problem from the cookbook with different AMR coarsening/refinement fraction numbers, the total mass seems not conserved as good as using the uniform global refinement as shown in the following graph.
![plot_mass_fem_time](https://cloud.githubusercontent.com/assets/12536604/15765551/d4ee9f7e-28ea-11e6-9650-b449f56b317f.png)

It seems that the coarsening/refinement fraction number combination (0.01, 0.9) is the best among those six AMR fraction numbers. For the Van Keken problem, it also seems that the coarsening number dominants the accuracy of the mass conservation. 

The default values of ASPECT are (0.05, 0.3). Consider the number of cells used (see the graph below) and the accuracy of the total mass conserved (graph above ), it's a relative good choice. Now I am wondering how the default number selected if anyone can answer that.  Is it worth to add more discussions on how to choose the right AMR fraction number in the manual for the general users? Perhaps it can be also mentioned somewhere in the manual that for those people interested in longtime simulation with requirement of  global mass conservation,  they should pay particular attention on how to choose the AMR fraction number?
![plot_max_c_fem_time](https://cloud.githubusercontent.com/assets/12536604/15765882/90ce0812-28ee-11e6-8bbe-0b06d1df0b07.png)

**Comment by yinghe616** [comment]
Figures of compositional field at final time = 2000 and their mesh attached.
Left figure: global refinement;
Middle figure: AMR default fraction numbers (0.05, 0.3)
Right figure: AMR fraction numbers (0.01,0.9)   
![c_mesh_three](https://cloud.githubusercontent.com/assets/12536604/15766621/6f0dbfae-28f5-11e6-8567-b167cea2c784.png)

**Comment by bangerth** [comment]
When you do mesh refinement/coarsening, the solution is interpolated from the old mesh to the new one. While the interpolation from a cell to its children (i.e., if it was refined) conserves the mass (because the function interpolated onto the children *equals* the original function on the parent cell), coarsening does not preserve mass. In other words, *any* coarsening you do will lead to a violation of the mass conservation, even if the scheme you use to go from one time step to the next is mass conservative. It should be relatively simple to test that if you set the coarsening fraction to zero, mass should be conserved.

I think this would be worthwhile stating in the manual at an appropriate place where mass conservation is mentioned. 

(And on how we arrived at the 0.05/0.3 fractions: these are, by trial and error, values we have often used for many kinds of simulations based on deal.II, and values others in the adaptive finite element community have also found to be useful. There is really not very much magic to it, other than that the have been found "to work" in the past. In addition, in 2d, a refinement fraction of 1/3 of the cells leads to a doubling of the number of cells, which is a useful property for stationary problems, see the text here: http://www.math.tamu.edu/~bangerth/videos.676.17.html ; the value has no particular meaning for time dependent problems.)

**Comment by yinghe616** [comment]
Thanks @bangerth for your quick explanation and clarification. :+1: 
I am glad that I asked the question as you just answered me another question that has been bothered me for a long time when I was working on the DG bound preserving limiter. For that test, I also found the results are very sensitive to the coarsening of mesh. I understood that the refinement doesn't change the basis function so the mass is conserved, however I thought that the coarsening mesh uses some L2  (or H1) projection from children to parent, so the mass is also conserved... Now I realized I was wrong. ^_^

**Comment by bangerth** [comment]
Yes, it's just interpolation. But note that the L2 or H1 projections *also* don't conserve mass. The L2 projection only preserves the L2 norm. In general, defining an operation between meshes that both conserves mass *and* preserves bounds is difficult for sure; I don't know the field well enough to even know whether it's possible.

**Comment by yinghe616** [comment]
I thought if it's a L2 projection, then we can let the test function to be
one, which becomes mass conservation... but the grid values will change. I
agree with you defining the operation between meshes that both conserves
mass and preserves bounds is really difficult ^_^.

**Comment by bangerth** [comment]
Oh, yes, you are of course correct with the L2 projection. (But indeed, the L2 projection does not preserve bounds.)

**Comment by bangerth** [comment]
What should we do here? There is not very much we can do about the issue, other than document it. 

@yinghe616 -- do you plan on writing a section about the limiter for the manual? If yes, then this would be the place to mention the issue. If not, maybe we should put writing such a section on the list of things that should eventually be done.

**Comment by yinghe616** [comment]
Yes, I do plan to write a section/cookbook about the limiter for the manual. I can mention the issue there.

@bangerth -- Do you know if there is a local L2 projection function in deal.ii? For FEM, I think it's not able to be resolved since it requires continuous between elements. Do a global L2/H1 projection is numerically expensive,  so I guess that's why a local interpolation is used between both parent to children or children to parent? However, for DG elements, the localized interpolation or projection is allowed, so I guess we can improve the mass conservation at least for the DG elements.

**Comment by bangerth** [comment]
That would be great if you could write a section for the manual.

Regarding the L2 projection: we currently let the `SolutionTransfer` class handle transfer between meshes, and it only knows about the interpolation. From what I recall from its implementation, it would take some serious revision of code to allow it to use anything other. The reason is that the L2 projection (or any other kind of projection, for that matter) takes the geometry of cells into account, whereas the current scheme does not. It's important to realize that the geometry of cells also requires the class to know about the mapping. None of this is currently available in `SolutionTransfer`. This may be a long-term project. It's definitely not easy to implement.

**Comment by gassmoeller** [comment]
I think we have settled that the current behavior, while not mass-conserving, is exactly what we expect it to be. To prevent confusion I will close this issue (it is marked as bug). Feel free to reopen or to open pull request for improvements of this issue.
